import type { Config, Context } from "@netlify/functions";
import { getDatabase } from "@netlify/database";
import crypto from "node:crypto";

const MASTER=()=>Netlify.env.get("GASI_MASTER_ACTOR_ID")||"GASI-MASTER-01";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"no-store"}});
const env=(name:string)=>Netlify.env.get(name)||"";
const b64=(v:Buffer|string)=>Buffer.from(v).toString("base64url");
const bearer=(req:Request)=>{const value=req.headers.get("authorization")||"";return value.startsWith("Bearer ")?value.slice(7):"";};
const profile=(w:any)=>({id:w.id,role:w.role,display_name:w.display_name,centers:w.centers||[],operational_state:w.active?"ACTIVE":"REVOKED",delegated_privileges:w.delegated_privileges||[]});
const has=(w:any,p:string)=>w.id===MASTER()||(w.delegated_privileges||[]).includes(p);
const required=(v:unknown,name:string)=>{const s=String(v||"").trim();if(!s)throw new Error(`${name}_required`);if(s.length>160)throw new Error(`${name}_too_long`);return s;};
function secret(){const value=env("GASI_INTERNAL_SESSION_SECRET");if(Buffer.byteLength(value)<32)throw new Error("session_secret_not_configured");return value;}
function sign(payload:any){const encoded=b64(JSON.stringify(payload));const sig=crypto.createHmac("sha256",secret()).update(encoded).digest("base64url");return `v1.${encoded}.${sig}`;}
function decode(token:string){const [version,encoded,supplied]=token.split(".");if(version!=="v1"||!encoded||!supplied)throw new Error("invalid_session_token");const expected=crypto.createHmac("sha256",secret()).update(encoded).digest("base64url");if(expected.length!==supplied.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(supplied)))throw new Error("invalid_session_token");const p=JSON.parse(Buffer.from(encoded,"base64url").toString("utf8"));if(!p.sub||!p.exp||!p.av||Date.now()>=Number(p.exp)*1000)throw new Error("session_expired_or_revoked");return p;}
async function actor(req:Request,db:any){const token=bearer(req);if(!token)throw new Error("missing_session");const p=decode(token);const rows=await db.sql`SELECT id,role,display_name,centers,active,auth_version,delegated_privileges FROM internal_clinical_workers WHERE id=${String(p.sub)} LIMIT 1`;const w=rows[0];if(!w||!w.active||Number(w.auth_version)!==Number(p.av))throw new Error("session_expired_or_revoked");return w;}
async function audit(db:any,w:any,action:string,metadata:any={}){const client=await db.pool.connect();try{await client.query("BEGIN");const last=await client.query("SELECT event_hash FROM internal_clinical_audit ORDER BY seq DESC LIMIT 1 FOR UPDATE");const previous=last.rows[0]?.event_hash||null;const at=new Date().toISOString();const canonical=JSON.stringify({at,actor_id:w.id,actor_role:w.role,action,episode_id:null,metadata,previous_hash:previous});const hash=crypto.createHash("sha256").update(canonical).digest("hex");await client.query("INSERT INTO internal_clinical_audit(at,actor_id,actor_role,action,metadata,previous_hash,event_hash) VALUES($1,$2,$3,$4,$5,$6,$7)",[at,w.id,w.role,action,metadata,previous,hash]);await client.query("COMMIT");}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
async function verifyPassword(password:string,stored:string){if(!stored.startsWith("scrypt$"))return false;const [,salt,key]=stored.split("$");if(!salt||!key)return false;const derived=await new Promise<Buffer>((resolve,reject)=>crypto.scrypt(password,salt,32,(e,d)=>e?reject(e):resolve(d as Buffer)));return key.length===derived.toString("hex").length&&crypto.timingSafeEqual(derived,Buffer.from(key,"hex"));}
const disciplineFor=(role:string)=>role==="psychologist"?"psychology":role==="physiotherapist"?"physiotherapy":"nursing";
const canRead=(w:any,e:any)=>w.role==="admin"||(Array.isArray(w.centers)&&w.centers.includes(e.center));
const canWrite=(w:any,e:any)=>w.role!=="admin"&&Array.isArray(w.centers)&&w.centers.includes(e.center)&&disciplineFor(w.role)===e.discipline;
const publicEpisode=(row:any,metadataOnly=false)=>{const d=row.document||{};return metadataOnly?{id:row.id,center:row.center,discipline:row.discipline,level:row.level,status:row.status,created_at:row.created_at}:{...d,id:row.id,center:row.center,patient_ref:row.patient_ref,discipline:row.discipline,level:row.level,status:row.status,created_at:row.created_at};};
async function hashPassword(password:string){if(password.length<12||password.length>128)throw new Error("invalid_temporary_password");const salt=crypto.randomBytes(16).toString("hex");const key=await new Promise<Buffer>((resolve,reject)=>crypto.scrypt(password,salt,32,(e,d)=>e?reject(e):resolve(d as Buffer)));return `scrypt$${salt}$${key.toString("hex")}`;}

export default async (req:Request,_context:Context)=>{const db=getDatabase();const url=new URL(req.url);const path=url.pathname;try{
 if(req.method==="GET"&&path==="/api/internal-clinical/health"){await db.sql`SELECT 1`;return json({ok:true,storage:"netlify-database"});}
 if(req.method==="POST"&&path==="/api/internal-clinical/login"){const body=await req.json() as any;const id=String(body.worker_id||"").trim();const rows=await db.sql`SELECT * FROM internal_clinical_workers WHERE id=${id} LIMIT 1`;const w=rows[0];if(!w||!w.active||!(await verifyPassword(String(body.password||""),w.password_hash)))return json({detail:"invalid_credentials"},401);const ttl=Math.min(480,Math.max(1,Number(env("GASI_INTERNAL_SESSION_TTL_MINUTES")||30)));const now=Math.floor(Date.now()/1000);const token=sign({sid:crypto.randomUUID(),sub:w.id,iat:now,exp:now+ttl*60,av:Number(w.auth_version)});await audit(db,w,"LOGIN_SUCCESS");return json({token,expires_at:new Date((now+ttl*60)*1000).toISOString(),profile:profile(w)});}
 const w=await actor(req,db);
 if(req.method==="GET"&&(path.endsWith("/session")||path.endsWith("/profile"))){await audit(db,w,path.endsWith("/session")?"SESSION_VALIDATED":"PROFILE_VIEWED");return json(path.endsWith("/session")?{...profile(w),active:true}:profile(w));}
 if(req.method==="POST"&&path.endsWith("/logout")){await db.sql`UPDATE internal_clinical_workers SET auth_version=auth_version+1 WHERE id=${w.id}`;await audit(db,w,"LOGOUT_ALL_SESSIONS");return json({ok:true});}
 if(req.method==="POST"&&path==="/api/internal-clinical/workers"){if(!has(w,"worker_access_management"))return json({detail:"worker_management_required"},403);const b=await req.json() as any;const id=required(b.id,"worker_id"),name=required(b.display_name,"display_name"),role=String(b.role||"");if(!["nurse","physician","psychologist","physiotherapist","admin"].includes(role))return json({detail:"invalid_role"},422);const centers=Array.isArray(b.centers)?b.centers.map((x:any)=>required(x,"center")):[];if(role==="admin"&&centers.length)return json({detail:"admin_cannot_have_clinical_centers"},422);if(role!=="admin"&&!centers.length)return json({detail:"clinical_worker_requires_center"},422);if(new Set(centers).size!==centers.length)return json({detail:"duplicate_centers"},422);const exists=await db.sql`SELECT id FROM internal_clinical_workers WHERE id=${id}`;if(exists.length)return json({detail:"worker_already_exists"},409);const password_hash=await hashPassword(String(b.temporary_password||""));await db.sql`INSERT INTO internal_clinical_workers(id,role,display_name,centers,active,auth_version,delegated_privileges,password_hash) VALUES(${id},${role},${name},${JSON.stringify(centers)}::jsonb,TRUE,1,'[]'::jsonb,${password_hash})`;await audit(db,w,"IDENTITY_CREATED",{target_actor_id:id,target_role:role,center_count:centers.length});return json({id,role,display_name:name,centers,operational_state:"ACTIVE",delegated_privileges:[]},201);}
 const access=path.match(/^\/api\/internal-clinical\/workers\/([^/]+)\/access$/);if(req.method==="POST"&&access){if(!has(w,"worker_access_management"))return json({detail:"worker_management_required"},403);const id=decodeURIComponent(access[1]);const rows=await db.sql`SELECT * FROM internal_clinical_workers WHERE id=${id}`;const target=rows[0];if(!target)return json({detail:"worker_not_found"},404);if(id===MASTER())return json({detail:"master_access_is_intrinsic"},409);const b=await req.json() as any;if(!["ACTIVE","REVOKED"].includes(b.state))return json({detail:"invalid_access_state"},422);if(id===w.id&&b.state==="REVOKED")return json({detail:"self_revocation_not_allowed"},409);const active=b.state==="ACTIVE";await db.sql`UPDATE internal_clinical_workers SET active=${active},auth_version=auth_version+1 WHERE id=${id}`;await audit(db,w,active?"IDENTITY_REACTIVATED":"IDENTITY_REVOKED",{target_actor_id:id,access_state:b.state});return json({...profile(target),operational_state:b.state});}
 const privilege=path.match(/^\/api\/internal-clinical\/workers\/([^/]+)\/privileges\/([^/]+)$/);if(req.method==="POST"&&privilege){if(w.id!==MASTER())return json({detail:"master_required"},403);const id=decodeURIComponent(privilege[1]),p=decodeURIComponent(privilege[2]);const rows=await db.sql`SELECT * FROM internal_clinical_workers WHERE id=${id}`;if(!rows[0])return json({detail:"worker_not_found"},404);const b=await req.json() as any;const grant=b.granted===true;await db.sql`UPDATE internal_clinical_workers SET delegated_privileges=CASE WHEN ${grant} THEN (SELECT jsonb_agg(DISTINCT x) FROM jsonb_array_elements_text(delegated_privileges || to_jsonb(${p}::text)) x) ELSE delegated_privileges - ${p} END,auth_version=auth_version+1 WHERE id=${id}`;await audit(db,w,grant?"PRIVILEGE_GRANTED":"PRIVILEGE_REVOKED",{target_actor_id:id,privilege:p});return json({ok:true});}
 if(req.method==="GET"&&path==="/api/internal-clinical/episodes"){const rows=await db.sql`SELECT * FROM internal_clinical_episodes ORDER BY created_at DESC LIMIT 250`;return json(rows.filter((e:any)=>canRead(w,e)).map((e:any)=>publicEpisode(e,w.role==="admin"))); }
 if(req.method==="POST"&&path==="/api/internal-clinical/episodes"){const b=await req.json() as any;if(w.role==="admin")return json({detail:"clinical_role_required"},403);const patient_ref=required(b.patient_ref,"patient_ref"),center=required(b.center,"center"),summary=required(b.summary,"summary"),level=Number(b.level);if(!w.centers?.includes(center))return json({detail:"assigned_center_required"},403);if(![1,2,3].includes(level))return json({detail:"invalid_level"},422);const discipline=disciplineFor(w.role);const client=await db.pool.connect();try{await client.query("BEGIN");const n=await client.query("UPDATE internal_clinical_counters SET value=value+1 WHERE name='episode' RETURNING value");const id=`GASI-EP-${String(n.rows[0].value).padStart(8,"0")}`;const created_at=new Date().toISOString();const document={summary,created_by_id:w.id,created_at,responses:[],addenda:[],level_history:[{level,actor_id:w.id,at:created_at}],disposition_events:[]};await client.query("INSERT INTO internal_clinical_episodes(id,center,patient_ref,discipline,level,status,document,created_at) VALUES($1,$2,$3,$4,$5,'OPEN',$6,$7)",[id,center,patient_ref,discipline,level,document,created_at]);await client.query("COMMIT");await audit(db,w,"EPISODE_CREATED",{episode_id:id,center,discipline,level});return json({id,center,patient_ref,discipline,level,status:"OPEN",...document},201);}catch(e){await client.query("ROLLBACK");throw e;}finally{client.release();}}
 const episodeMatch=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)$/);if(req.method==="GET"&&episodeMatch){const id=decodeURIComponent(episodeMatch[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canRead(w,e))return json({detail:"episode_access_denied"},403);await audit(db,w,"EPISODE_VIEWED",{episode_id:id,metadata_only:w.role==="admin"});return json(publicEpisode(e,w.role==="admin"));}
 const levelMatch=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/level$/);if(req.method==="POST"&&levelMatch){const id=decodeURIComponent(levelMatch[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);if(e.status==="CLOSED")return json({detail:"closed_episode_immutable"},409);const b=await req.json() as any,level=Number(b.level);if(![1,2,3].includes(level))return json({detail:"invalid_level"},422);const at=new Date().toISOString(),doc=e.document||{};doc.level_history=[...(doc.level_history||[]),{level,actor_id:w.id,at}];await db.sql`UPDATE internal_clinical_episodes SET level=${level},document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"LEVEL_CHANGED",{episode_id:id,level});return json({...publicEpisode({...e,level,document:doc})});}
 const responseMatch=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/responses$/);if(req.method==="POST"&&responseMatch){const id=decodeURIComponent(responseMatch[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);if(e.status==="CLOSED")return json({detail:"closed_episode_immutable"},409);const b=await req.json() as any,text=required(b.text,"response_text"),at=new Date().toISOString(),doc=e.document||{};const response={id:crypto.randomUUID(),text,author_id:w.id,created_at:at,status_history:[],corrections:[]};doc.responses=[...(doc.responses||[]),response];await db.sql`UPDATE internal_clinical_episodes SET document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"RESPONSE_ADDED",{episode_id:id,response_id:response.id});return json(publicEpisode({...e,document:doc}));}
 const addendumMatch=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/addenda$/);if(req.method==="POST"&&addendumMatch){const id=decodeURIComponent(addendumMatch[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);if(e.status==="CLOSED")return json({detail:"closed_episode_immutable"},409);const b=await req.json() as any,text=required(b.text,"addendum_text"),at=new Date().toISOString(),doc=e.document||{};const item={id:crypto.randomUUID(),text,author_id:w.id,author_role:w.role,created_at:at,corrections:[]};doc.addenda=[...(doc.addenda||[]),item];await db.sql`UPDATE internal_clinical_episodes SET document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"ADDENDUM_ADDED",{episode_id:id,addendum_id:item.id});return json(publicEpisode({...e,document:doc}));}
 const correct=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/(responses|addenda)\/([^/]+)\/correct$/);if(req.method==="POST"&&correct){const id=decodeURIComponent(correct[1]),kind=correct[2],itemId=decodeURIComponent(correct[3]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);const b=await req.json() as any,replacement=required(b.replacement_text,"replacement_text"),reason=required(b.reason,"reason"),doc=e.document||{},key=kind==="responses"?"responses":"addenda",items=doc[key]||[],idx=items.findIndex((x:any)=>x.id===itemId);if(idx<0)return json({detail:"clinical_entry_not_found"},404);const at=new Date().toISOString(),old=items[idx].text;items[idx]={...items[idx],text:replacement,corrections:[...(items[idx].corrections||[]),{previous_text:old,replacement_text:replacement,reason,corrected_by_id:w.id,corrected_at:at}]};doc[key]=items;await db.sql`UPDATE internal_clinical_episodes SET document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"CLINICAL_ENTRY_CORRECTED",{episode_id:id,entry_id:itemId,entry_kind:kind,reason});return json(publicEpisode({...e,document:doc}));}
 const closeMatch=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/close$/);if(req.method==="POST"&&closeMatch){const id=decodeURIComponent(closeMatch[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);if(e.status==="CLOSED")return json({detail:"episode_already_closed"},409);const b=await req.json() as any,reason=required(b.reason||b.closure_reason,"closure_reason"),at=new Date().toISOString(),doc=e.document||{};doc.closed_at=at;doc.closed_by_id=w.id;doc.closure_reason=reason;await db.sql`UPDATE internal_clinical_episodes SET status='CLOSED',document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"EPISODE_CLOSED",{episode_id:id,reason});return json(publicEpisode({...e,status:"CLOSED",document:doc}));}
 const privileged=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/privileged-access$/);if(req.method==="POST"&&privileged){const id=decodeURIComponent(privileged[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!has(w,"clinical_privileged_read"))return json({detail:"privileged_access_required"},403);if(w.id!==MASTER()&&!w.centers?.includes(e.center))return json({detail:"privileged_access_center_denied"},403);const b=await req.json() as any,reason=required(b.reason,"reason"),reference=required(b.reference,"reference");await audit(db,w,"PRIVILEGED_EPISODE_ACCESSED",{episode_id:id,reason,reference,delegated:w.id!==MASTER()});return json({...publicEpisode(e),privileged_access:{read_only:true,reason,reference}});}
 const disposition=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/disposition$/);if(req.method==="POST"&&disposition){const id=decodeURIComponent(disposition[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);if(e.status==="CLOSED")return json({detail:"closed_episode_immutable"},409);const b=await req.json() as any,kind=required(b.kind,"disposition_kind"),occurred_at=required(b.occurred_at,"occurred_at"),doc=e.document||{};const event={id:crypto.randomUUID(),kind,occurred_at,recorded_at:new Date().toISOString(),recorded_by_id:w.id,recorded_by_role:w.role};doc.disposition_events=[...(doc.disposition_events||[]),event];await db.sql`UPDATE internal_clinical_episodes SET document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"DISPOSITION_RECORDED",{episode_id:id,disposition_id:event.id,kind});return json(publicEpisode({...e,document:doc}));}
 const responseDelivery=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/responses\/([^/]+)\/delivery$/);if(req.method==="POST"&&responseDelivery){const id=decodeURIComponent(responseDelivery[1]),responseId=decodeURIComponent(responseDelivery[2]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);const b=await req.json() as any,kind=String(b.kind||""),map:any={delivered:"DELIVERED",read:"READ",failed:"DELIVERY_FAILED",alternate_channel:"ALTERNATE_CHANNEL_REQUIRED",DELIVERED:"DELIVERED",READ:"READ",DELIVERY_FAILED:"DELIVERY_FAILED",ALTERNATE_CHANNEL_REQUIRED:"ALTERNATE_CHANNEL_REQUIRED"},state=map[kind];if(!state)return json({detail:"invalid_delivery_state"},422);const doc=e.document||{},responses=doc.responses||[],idx=responses.findIndex((x:any)=>x.id===responseId);if(idx<0)return json({detail:"response_not_found"},404);const history=responses[idx].status_history||[],last=history.at(-1);if(state==="READ"&&last?.state!=="DELIVERED")return json({detail:"read_requires_delivery"},409);if(state==="DELIVERY_FAILED"&&["DELIVERED","READ"].includes(last?.state))return json({detail:"proven_delivery_cannot_fail"},409);if(state==="ALTERNATE_CHANNEL_REQUIRED"&&last?.state!=="DELIVERY_FAILED")return json({detail:"alternate_channel_requires_failure"},409);let reason="";if(state==="DELIVERY_FAILED")reason=required(b.failure_reason||b.reason,"failure_reason");if(state==="ALTERNATE_CHANNEL_REQUIRED")reason=required(b.reason,"reason");const event={state,at:b.at||new Date().toISOString(),actor_id:w.id,...(reason?{reason}:{})};responses[idx]={...responses[idx],status_history:[...history,event]};doc.responses=responses;await db.sql`UPDATE internal_clinical_episodes SET document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"RESPONSE_DELIVERY_STATE_CHANGED",{episode_id:id,response_id:responseId,state,...(reason?{reason}:{})});return json(event);}
 const delivery=path.match(/^\/api\/internal-clinical\/episodes\/([^/]+)\/delivery$/);if(req.method==="POST"&&delivery){const id=decodeURIComponent(delivery[1]);const rows=await db.sql`SELECT * FROM internal_clinical_episodes WHERE id=${id} LIMIT 1`;const e=rows[0];if(!e)return json({detail:"episode_not_found"},404);if(!canWrite(w,e))return json({detail:"episode_write_denied"},403);const b=await req.json() as any,state=String(b.state||""),doc=e.document||{},history=doc.delivery_history||[],last=history.at(-1);if(!["DELIVERED","READ","DELIVERY_FAILED","ALTERNATE_CHANNEL_REQUIRED"].includes(state))return json({detail:"invalid_delivery_state"},422);if(state==="READ"&&last?.state!=="DELIVERED")return json({detail:"read_requires_delivery"},409);if(state==="DELIVERY_FAILED"&&["DELIVERED","READ"].includes(last?.state))return json({detail:"proven_delivery_cannot_fail"},409);if(state==="ALTERNATE_CHANNEL_REQUIRED"&&last?.state!=="DELIVERY_FAILED")return json({detail:"alternate_channel_requires_failure"},409);let reason="";if(state==="DELIVERY_FAILED"){reason=required(b.failure_reason,"failure_reason");}if(state==="ALTERNATE_CHANNEL_REQUIRED"){reason=required(b.reason,"reason");}const event={state,at:new Date().toISOString(),actor_id:w.id,...(reason?{reason}:{})};doc.delivery_history=[...history,event];await db.sql`UPDATE internal_clinical_episodes SET document=${JSON.stringify(doc)}::jsonb WHERE id=${id}`;await audit(db,w,"DELIVERY_STATE_CHANGED",{episode_id:id,state,...(reason?{reason}:{})});return json({episode_id:id,delivery:event,delivery_history:doc.delivery_history});}
 return json({detail:"netlify_clinical_route_not_migrated"},501);
}catch(e:any){const code=String(e?.message||"internal_error");if(["missing_session","invalid_session_token","session_expired_or_revoked"].includes(code))return json({detail:code},401);if(code.endsWith("_required")||code.endsWith("_too_long")||code==="invalid_temporary_password")return json({detail:code},422);return json({detail:"internal_error"},500);}};
export const config:Config={path:"/api/internal-clinical/*"};
