import React,{useEffect,useState}from'react';

const disciplineFor=role=>role==='psychologist'?'psychology':role==='physiotherapist'?'physiotherapy':'nursing';

export default function InternalClinicalEpisodeActions({episode,session,api,onUpdate,readOnly=false}){
 const[responseText,setResponseText]=useState('');
 const[addendumText,setAddendumText]=useState('');
 const[busy,setBusy]=useState('');
 const[message,setMessage]=useState('');
 const[levelValue,setLevelValue]=useState(Number(episode?.level)||2);
 const[dispositionKind,setDispositionKind]=useState('');
 const[dispositionAt,setDispositionAt]=useState('');
 const[deliveryReason,setDeliveryReason]=useState('');
 const[noFollowUp,setNoFollowUp]=useState(false);
 const[handoffRequired,setHandoffRequired]=useState(false);
 const[handoffAcknowledged,setHandoffAcknowledged]=useState(false);
 const[acknowledgementRequired,setAcknowledgementRequired]=useState(false);
 useEffect(()=>{setLevelValue(Number(episode?.level)||2);setDispositionKind('');setDispositionAt('');},[episode?.id,episode?.level]);
 if(!episode||!session||!api||readOnly)return null;
 const canWrite=session.role!=='admin'&&Array.isArray(session.centers)&&session.centers.includes(episode.center)&&disciplineFor(session.role)===episode.discipline;
 const canRespond=['physician','psychologist','physiotherapist'].includes(session.role);
 const responseLabel=session.role==='physician'?'Respuesta facultativa':session.role==='psychologist'?'Respuesta de Psicología':'Respuesta de Fisioterapia';
 if(!canWrite||episode.status==='CERRADO')return null;
 const responses=Array.isArray(episode.responses)?episode.responses:[];
 const latestResponse=responses.at(-1)||null;
 const pendingLate=responses.filter(r=>r.lateAfterDisposition&&!r.lateReviewedAt);
 const deliveryHistory=Array.isArray(episode.deliveryHistory)?episode.deliveryHistory:[];
 const latestDelivery=deliveryHistory.at(-1)||null;
 const refresh=async()=>{const updated=await api.getEpisode(episode.id);onUpdate(updated);return updated;};
 const respond=async e=>{e.preventDefault();const text=responseText.trim();if(!text)return;setBusy('response');setMessage('');try{const updated=await api.respond(episode.id,text);onUpdate(updated);setResponseText('');setMessage('Respuesta profesional registrada.');}catch(err){setMessage(`Respuesta rechazada: ${err.code||'error'}`);}finally{setBusy('');}};
 const addendum=async e=>{e.preventDefault();const text=addendumText.trim();if(!text)return;setBusy('addendum');setMessage('');try{const updated=await api.addAddendum(episode.id,text);onUpdate(updated);setAddendumText('');setMessage('Anotación registrada.');}catch(err){setMessage(`Anotación rechazada: ${err.code||'error'}`);}finally{setBusy('');}};
 const changeLevel=async e=>{e.preventDefault();if(episode.discipline!=='nursing'||Number(levelValue)===Number(episode.level))return;setBusy('level');setMessage('');try{const updated=await api.changeLevel(episode.id,Number(levelValue));onUpdate(updated);setMessage('Nivel actualizado y trazado.');}catch(err){setMessage(`Cambio de nivel rechazado: ${err.code||'error'}`);}finally{setBusy('');}};
 const recordDisposition=async e=>{e.preventDefault();const kind=dispositionKind.trim(),millis=Date.parse(dispositionAt);if(!kind||!Number.isFinite(millis))return;setBusy('disposition');setMessage('');try{const updated=await api.recordDisposition(episode.id,kind,new Date(millis).toISOString());onUpdate(updated);setDispositionKind('');setDispositionAt('');setMessage('Disposición registrada.');}catch(err){setMessage(`Disposición rechazada: ${err.code||'error'}`);}finally{setBusy('');}};
 const reviewLate=async responseId=>{setBusy(`review-${responseId}`);setMessage('');try{await api.reviewLateResponse(episode.id,responseId);await refresh();setMessage('Respuesta tardía revisada y registrada.');}catch(err){setMessage(`Revisión rechazada: ${err.code||'error'}`);}finally{setBusy('');}};
 const advance=async(kind,label)=>{if(!latestResponse)return;setBusy(kind);setMessage('');try{await api.advanceMessage(episode.id,latestResponse.id,kind);await refresh();setMessage(label);}catch(err){setMessage(`Estado de entrega rechazado: ${err.code||'error'}`);}finally{setBusy('');}};
 const recordEpisodeDelivery=async state=>{const reason=deliveryReason.trim(),payload={state};if(state==='DELIVERY_FAILED'){if(!reason)return;payload.failure_reason=reason;}if(state==='ALTERNATE_CHANNEL_REQUIRED'){if(!reason)return;payload.reason=reason;}setBusy(`delivery-${state}`);setMessage('');try{await api.recordDeliveryState(episode.id,payload);await refresh();setDeliveryReason('');setMessage('Estado de comunicación registrado.');}catch(err){setMessage(`Contingencia de comunicación rechazada: ${err.code||'error'}`);}finally{setBusy('');}};
 const close=async e=>{e.preventDefault();setBusy('close');setMessage('');try{const updated=await api.closeEpisode(episode.id,{follow_up_pending:!noFollowUp,handoff_required:handoffRequired,handoff_acknowledged:handoffAcknowledged,acknowledgement_required:acknowledgementRequired});onUpdate(updated);setMessage('Episodio cerrado.');}catch(err){setMessage(`Cierre rechazado: ${err.code||'error'}`);}finally{setBusy('');}};
 const canClose=episode.status==='RESPONDIDO'&&noFollowUp&&pendingLate.length===0&&(!handoffRequired||handoffAcknowledged)&&(!acknowledgementRequired||latestResponse?.status==='LEIDA');
 return <section className="mt-5 rounded-xl border border-slate-800 bg-slate-900 p-5" aria-busy={Boolean(busy)}>
  <h2 className="font-bold">Actuación clínica</h2>
  <p className="mt-1 text-sm text-slate-400">Las acciones se registran con tu identidad y conservan la trazabilidad del episodio.</p>
  {episode.discipline==='nursing'&&<form onSubmit={changeLevel} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label className="block text-sm">Nivel de prioridad<select value={levelValue} onChange={e=>setLevelValue(Number(e.target.value))} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-3"><option value={1}>N1 · Urgencia</option><option value={2}>N2 · Consulta no aguda</option><option value={3}>N3 · Gestión</option></select></label><button disabled={busy!==''||Number(levelValue)===Number(episode.level)} className="rounded border border-cyan-400 px-4 py-3 font-semibold disabled:opacity-50">{busy==='level'?'Actualizando…':'Cambiar nivel'}</button></form>}
  <form onSubmit={recordDisposition} className="mt-5 border-t border-slate-800 pt-4"><h3 className="font-semibold">Disposición / resultado del episodio</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="block text-sm">Tipo<input required maxLength={160} value={dispositionKind} onChange={e=>setDispositionKind(e.target.value)} placeholder="Ej.: derivación, alta, traspaso" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-3"/></label><label className="block text-sm">Fecha y hora<input type="datetime-local" required value={dispositionAt} onChange={e=>setDispositionAt(e.target.value)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-3"/></label></div><button disabled={busy!==''||!dispositionKind.trim()||!dispositionAt} className="mt-3 rounded border border-slate-600 px-4 py-2 font-semibold disabled:opacity-50">{busy==='disposition'?'Registrando…':'Registrar disposición'}</button></form>
  {canRespond&&<form onSubmit={respond} className="mt-5 border-t border-slate-800 pt-4">
   <label className="block text-sm">{responseLabel}<textarea required minLength={2} maxLength={10000} value={responseText} onChange={e=>setResponseText(e.target.value)} className="mt-1 min-h-28 w-full rounded border border-slate-700 bg-slate-950 p-3"/></label>
   <button disabled={busy!==''||!responseText.trim()} className="mt-3 rounded bg-cyan-300 px-4 py-2 font-bold text-slate-950 disabled:opacity-50">{busy==='response'?'Registrando…':'Emitir respuesta'}</button>
  </form>}
  <form onSubmit={addendum} className="mt-5 border-t border-slate-800 pt-4">
   <label className="block text-sm">Anotación / adenda<textarea required minLength={2} maxLength={10000} value={addendumText} onChange={e=>setAddendumText(e.target.value)} className="mt-1 min-h-24 w-full rounded border border-slate-700 bg-slate-950 p-3"/></label>
   <button disabled={busy!==''||!addendumText.trim()} className="mt-3 rounded border border-cyan-400 px-4 py-2 font-semibold disabled:opacity-50">{busy==='addendum'?'Registrando…':'Añadir anotación'}</button>
  </form>
  {pendingLate.length>0&&<div className="mt-5 border-t border-amber-500/30 pt-4"><h3 className="font-semibold text-amber-200">Respuestas tardías pendientes de revisión</h3><div className="mt-2 space-y-2">{pendingLate.map(r=><button type="button" key={r.id} disabled={busy!==''||r.authorId===session.id} onClick={()=>reviewLate(r.id)} className="block rounded border border-amber-400/50 px-3 py-2 text-sm disabled:opacity-50">Revisar respuesta de {r.authorId}{r.authorId===session.id?' · no se permite autorrevisión':''}</button>)}</div></div>}
  <div className="mt-5 border-t border-slate-800 pt-4"><h3 className="font-semibold">Contingencia de comunicación del episodio</h3><p className="mt-1 text-sm text-slate-400">Estado actual: {latestDelivery?.state||'SIN REGISTRO'}</p>{(!latestDelivery||latestDelivery.state==='ALTERNATE_CHANNEL_REQUIRED')&&<div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy!==''} onClick={()=>recordEpisodeDelivery('DELIVERED')} className="rounded border border-emerald-500/50 px-3 py-2 text-sm">Confirmar entrega</button><button type="button" disabled={busy!==''||!deliveryReason.trim()} onClick={()=>recordEpisodeDelivery('DELIVERY_FAILED')} className="rounded border border-rose-500/50 px-3 py-2 text-sm">Registrar fallo</button></div>}{latestDelivery?.state==='DELIVERY_FAILED'&&<button type="button" disabled={busy!==''||!deliveryReason.trim()} onClick={()=>recordEpisodeDelivery('ALTERNATE_CHANNEL_REQUIRED')} className="mt-3 rounded border border-amber-400/50 px-3 py-2 text-sm">Requerir canal alternativo</button>}{latestDelivery?.state==='DELIVERED'&&<button type="button" disabled={busy!==''} onClick={()=>recordEpisodeDelivery('READ')} className="mt-3 rounded border border-cyan-400/50 px-3 py-2 text-sm">Registrar lectura</button>}{latestDelivery?.state!=='READ'&&latestDelivery?.state!=='DELIVERED'&&<label className="mt-3 block text-sm">Motivo de fallo / contingencia<input maxLength={1000} value={deliveryReason} onChange={e=>setDeliveryReason(e.target.value)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 p-3"/></label>}{latestDelivery?.state==='READ'&&<p className="mt-2 text-sm text-emerald-300">Lectura confirmada.</p>}</div>
  {latestResponse&&<div className="mt-5 border-t border-slate-800 pt-4"><h3 className="font-semibold">Entrega de la última respuesta</h3><p className="mt-1 text-sm text-slate-400">Estado actual: {latestResponse.status}</p>{latestResponse.status==='EMITIDA'&&<button type="button" disabled={busy!==''} onClick={()=>advance('delivery_receipt','Entrega registrada.')} className="mt-2 rounded border border-slate-600 px-3 py-2 text-sm">Registrar entrega</button>}{latestResponse.status==='ENTREGADA'&&<button type="button" disabled={busy!==''} onClick={()=>advance('read_receipt','Lectura registrada.')} className="mt-2 rounded border border-slate-600 px-3 py-2 text-sm">Registrar lectura</button>}</div>}
  {episode.status==='RESPONDIDO'&&<form onSubmit={close} className="mt-5 border-t border-slate-800 pt-4"><h3 className="font-semibold">Cierre del episodio</h3><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={noFollowUp} onChange={e=>setNoFollowUp(e.target.checked)}/>Confirmo que no queda seguimiento pendiente</label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={handoffRequired} onChange={e=>{setHandoffRequired(e.target.checked);if(!e.target.checked)setHandoffAcknowledged(false);}}/>El caso requiere traspaso</label>{handoffRequired&&<label className="mt-2 ml-6 flex gap-2 text-sm"><input type="checkbox" checked={handoffAcknowledged} onChange={e=>setHandoffAcknowledged(e.target.checked)}/>Traspaso confirmado</label>}<label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={acknowledgementRequired} onChange={e=>setAcknowledgementRequired(e.target.checked)}/>Exigir constancia de lectura antes de cerrar</label>{acknowledgementRequired&&latestResponse?.status!=='LEIDA'&&<p role="status" className="mt-2 text-sm text-amber-200">La última respuesta debe constar como leída antes del cierre.</p>}{pendingLate.length>0&&<p role="status" className="mt-2 text-sm text-amber-200">Hay respuestas tardías pendientes de revisión.</p>}<button disabled={busy!==''||!canClose} className="mt-3 rounded bg-emerald-300 px-4 py-2 font-bold text-slate-950 disabled:opacity-50">{busy==='close'?'Cerrando…':'Cerrar episodio'}</button></form>}
  {message&&<p role="status" aria-live="polite" className="mt-3 text-sm text-cyan-100">{message}</p>}
 </section>;
}
