import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
const source=fs.readFileSync(new URL("../functions/internal-clinical.mts",import.meta.url),"utf8");

test("attendance requires authenticated professional and registered active workstation",()=>{
 assert.ok(source.includes('attendance\\/(clock-in|clock-out)'),"attendance route matcher missing");
 assert.match(source,/w\.role==="admin".*professional_role_required/);
 assert.match(source,/internal_center_workstations WHERE id=/);
 assert.match(source,/!ws\|\|!ws\.active\|\|!\(await verifyPassword\(credential,ws\.credential_hash\)\)/);
});
test("workstation center must belong to worker",()=>{
 assert.match(source,/!Array\.isArray\(w\.centers\)\|\|!w\.centers\.includes\(ws\.center\)/);
 assert.match(source,/workstation_center_denied/);
});
test("open shift state is deterministic",()=>{
 assert.match(source,/shift_already_open/);
 assert.match(source,/no_open_shift/);
 assert.match(source,/eventType==="CLOCK_IN"&&last\?\.event_type==="CLOCK_IN"/);
 assert.match(source,/eventType==="CLOCK_OUT"&&last\?\.event_type!=="CLOCK_IN"/);
});
test("attendance timestamp is database generated and event is audited",()=>{
 assert.match(source,/INSERT INTO internal_attendance_events\(worker_id,center,workstation_id,event_type,actor_id\)/);
 const attendanceRoute=source.slice(source.indexOf("const attendance=path.match"),source.indexOf("if(req.method===\"GET\"&&path===\"/api/internal-clinical/workers\""));
 assert.ok(!attendanceRoute.includes("occurred_at) VALUES"),"attendance insert must use database timestamp");
 assert.match(source,/ATTENDANCE_CLOCKED_IN/);
 assert.match(source,/ATTENDANCE_CLOCKED_OUT/);
});

test("only master can enroll or change workstation state and raw credential is never persisted",()=>{
 assert.match(source,/path==="\/api\/internal-clinical\/workstations".*w\.id!==MASTER\(\).*master_account_only/);
 assert.match(source,/bcrypt\.hash\(credential,12\)/);
 assert.match(source,/INSERT INTO internal_center_workstations\(id,center,label,credential_hash,active\)/);
 assert.ok(!source.includes("credential,active)"),"raw workstation credential must not be persisted");
 assert.match(source,/WORKSTATION_REGISTERED/);
 assert.match(source,/WORKSTATION_REVOKED/);
});

test("attendance corrections are separate privileged audited events",()=>{
 assert.match(source,/attendance\\\/\(\[\^\/\]\+\)\\\/correct/);
 assert.match(source,/worker_access_management/);
 assert.match(source,/event_type,related_event_seq,reason,actor_id,metadata\) VALUES/);
 assert.match(source,/'CORRECTION'/);
 assert.match(source,/ATTENDANCE_CORRECTION_RECORDED/);
 const correctionStart=source.indexOf("const attendanceCorrection=path.match");
 assert.ok(correctionStart>=0,"attendance correction route missing");
 const correctionRoute=source.slice(correctionStart,correctionStart+2200);
 assert.doesNotMatch(correctionRoute,/UPDATE internal_attendance_events/);
 assert.doesNotMatch(correctionRoute,/DELETE FROM internal_attendance_events/);
});

test("attendance history prevents horizontal worker access",()=>{
 assert.match(source,/path==="\/api\/internal-clinical\/attendance"/);
 assert.match(source,/w\.role==="admin".*w\.id!==MASTER\(\).*attendance_global_read_denied/);
 assert.match(source,/internal_attendance_events WHERE worker_id=\$\{w\.id\}/);
 assert.doesNotMatch(source,/url\.searchParams\.get\("worker_id"\)/);
});


test("workstation credential is generated by the server and returned only at registration",()=>{
 const start=source.indexOf('path==="/api/internal-clinical/workstations"');
 assert.ok(start>=0,"workstation registration route missing");
 const route=source.slice(start,start+1800);
 assert.match(route,/crypto\.randomBytes\(32\)\.toString\("base64url"\)/);
 assert.doesNotMatch(route,/b\.credential/);
 assert.match(route,/bcrypt\.hash\(credential,12\)/);
 assert.match(route,/workstation_credential:credential/);
 assert.doesNotMatch(route,/credential_hash:credential/);
});

test("attendance state transition is serialized per worker",()=>{
 const attendanceStart=source.indexOf("const attendance=path.match");
 assert.ok(attendanceStart>=0,"attendance route missing");
 const attendanceRoute=source.slice(attendanceStart,attendanceStart+4200);
 assert.match(attendanceRoute,/db\.pool\.connect\(\)/);
 assert.match(attendanceRoute,/client\.query\("BEGIN"\)/);
 assert.match(attendanceRoute,/pg_advisory_xact_lock\(hashtext\(\$1\)\)/);
 const lockAt=attendanceRoute.indexOf("pg_advisory_xact_lock");
 const stateAt=attendanceRoute.indexOf("SELECT seq,event_type,occurred_at");
 const insertAt=attendanceRoute.indexOf("INSERT INTO internal_attendance_events");
 assert.ok(lockAt>=0&&stateAt>lockAt&&insertAt>stateAt,"lock must precede state check and insert");
 assert.match(attendanceRoute,/client\.query\("COMMIT"\)/);
 assert.match(attendanceRoute,/client\.query\("ROLLBACK"\)/);
 assert.match(attendanceRoute,/client\.release\(\)/);
});


test("administrative worker-management privilege does not grant global attendance read",()=>{
 const start=source.indexOf('if(req.method==="GET"&&path==="/api/internal-clinical/attendance")');
 assert.ok(start>=0,"attendance history route missing");
 const route=source.slice(start,start+1700);
 assert.match(route,/w\.role==="admin"/);
 assert.match(route,/w\.id!==MASTER\(\).*attendance_global_read_denied/);
 assert.doesNotMatch(route,/has\(w,"worker_access_management"\).*SELECT seq,worker_id,center/);
 assert.match(route,/ATTENDANCE_GLOBAL_VIEWED/);
 assert.match(route,/WHERE worker_id=\$\{w\.id\}/);
});
