import React from'react';
import{Link}from'react-router-dom';
import{ArrowRight,BookOpen,BriefcaseMedical,GraduationCap,HeartPulse,Users}from'lucide-react';

const blocks=[
 {icon:HeartPulse,title:'Primeros auxilios y respuesta inicial',text:'Actuación ante incidencias frecuentes, valoración inicial y criterios de activación de recursos.'},
 {icon:BriefcaseMedical,title:'Reanimación cardiopulmonar y soporte vital básico',text:'Entrenamiento práctico orientado a reconocer una parada, iniciar maniobras y utilizar un desfibrilador externo automatizado cuando proceda.'},
 {icon:BookOpen,title:'Detección del deterioro clínico',text:'Formación para reconocer cambios relevantes, priorizar y comunicar de forma estructurada.'},
 {icon:Users,title:'Programas adaptados al centro',text:'Contenido ajustado al perfil de actividad, turnos, riesgos operativos y nivel previo de los participantes.'}
];

export default function FormacionSanitaria(){
 return <div data-testid="formacion-page">
  <section className="relative min-h-[560px] flex items-center overflow-hidden bg-slate-950 text-white">
   <img src="https://images.pexels.com/photos/36346116/pexels-photo-36346116/free-photo-of-hands-on-cpr-training-session-in-buenos-aires.jpeg?auto=compress&dpr=1&h=750&w=1260" alt="Sesión práctica de reanimación cardiopulmonar" className="absolute inset-0 w-full h-full object-cover opacity-35"/>
   <div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/80 to-transparent"/>
   <div className="relative max-w-7xl mx-auto px-6 py-24 w-full"><div className="max-w-3xl"><p className="text-cyan-300 font-semibold uppercase tracking-wide text-sm">Formación sanitaria</p><h1 className="text-4xl lg:text-6xl font-bold mt-3">Formación que prepara para actuar, no solo para completar un curso</h1><p className="text-xl text-slate-200 mt-6 leading-relaxed">Programas para empresas y profesionales con contenidos prácticos, casos y objetivos definidos según el contexto de trabajo.</p><Link to="/contacto" className="inline-flex items-center mt-8 bg-white text-[#005EB8] font-bold px-6 py-3 rounded-xl">Solicitar propuesta <ArrowRight className="ml-2 w-5 h-5"/></Link></div></div>
  </section>
  <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-6"><div className="max-w-3xl"><p className="text-[#005EB8] font-semibold uppercase text-sm tracking-wide">Qué podemos preparar</p><h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mt-2">Formación sanitaria para equipos de trabajo</h2><p className="text-lg text-slate-600 mt-5">La formación puede plantearse como acción independiente o como complemento de una cobertura sanitaria. Duración, modalidad y profundidad se definen según el grupo y los objetivos.</p></div><div className="grid md:grid-cols-2 gap-6 mt-12">{blocks.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border bg-slate-50 p-7"><div className="w-12 h-12 rounded-xl bg-[#005EB8]/10 text-[#005EB8] flex items-center justify-center"><Icon className="w-6 h-6"/></div><h3 className="text-xl font-bold text-slate-900 mt-5">{title}</h3><p className="text-slate-600 mt-3 leading-relaxed">{text}</p></article>)}</div></div></section>
  <section className="py-20 bg-[#F3F7FB]"><div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center"><div><p className="text-[#005EB8] font-semibold uppercase text-sm tracking-wide">Metodología</p><h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mt-2">Contenido útil para el entorno real</h2><div className="space-y-5 mt-7 text-slate-600 text-lg"><p><strong className="text-slate-900">Casos y práctica.</strong> Priorizamos situaciones reconocibles y decisiones operativas.</p><p><strong className="text-slate-900">Nivel ajustado al grupo.</strong> No recibe el mismo programa un equipo general que profesionales sanitarios.</p><p><strong className="text-slate-900">Formato flexible.</strong> Presencial, online o combinado cuando el contenido lo permita.</p><p><strong className="text-slate-900">Material propio.</strong> Guías y recursos preparados para que la formación no dependa únicamente de la sesión.</p></div></div><div className="rounded-3xl bg-slate-950 text-white p-9"><GraduationCap className="w-12 h-12 text-cyan-300"/><h3 className="text-2xl font-bold mt-5">¿Busca un curso concreto?</h3><p className="text-slate-300 mt-3">Indíquenos número de participantes, perfil profesional, centro y objetivo. Le proponemos una estructura realista antes de presupuestar.</p><Link to="/contacto" className="inline-flex items-center mt-7 text-cyan-300 font-bold">Hablar con coordinación <ArrowRight className="ml-2 w-5 h-5"/></Link></div></div></section>
 </div>;
}
