import React from'react';
import{Link}from'react-router-dom';
import{ArrowRight,Building2,GraduationCap,HeartPulse,Network,ShieldCheck,Users}from'lucide-react';

const services=[
 {title:'Cobertura sanitaria en empresas',text:'Enfermería presencial y circuitos de apoyo definidos para cada centro.',link:'/cobertura-sanitaria',image:'https://images.pexels.com/photos/3952137/pexels-photo-3952137.jpeg?auto=compress&dpr=1&h=750&w=1260',icon:Building2},
 {title:'Servicios sanitarios complementarios',text:'Fisioterapia, psicología y apoyo médico remoto cuando la configuración lo justifique.',link:'/servicios-sanitarios-organizaciones',image:'https://images.pexels.com/photos/5793695/pexels-photo-5793695.jpeg?auto=compress&dpr=1&h=750&w=1260',icon:HeartPulse},
 {title:'Formación sanitaria',text:'Programas prácticos para equipos y profesionales, adaptados al entorno real de trabajo.',link:'/formacion-sanitaria',image:'https://images.pexels.com/photos/36346116/pexels-photo-36346116/free-photo-of-hands-on-cpr-training-session-in-buenos-aires.jpeg?auto=compress&dpr=1&h=750&w=1260',icon:GraduationCap}
];

const strengths=[
 {icon:Users,title:'Profesionales definidos por servicio',text:'Cada propuesta concreta qué perfiles intervienen y con qué alcance.'},
 {icon:Network,title:'Coordinación asistencial',text:'Circuitos claros entre presencia en centro, apoyo remoto y escalado.'},
 {icon:ShieldCheck,title:'Trazabilidad y seguridad',text:'Accesos, registros y cambios diseñados para un uso sanitario real.'}
];

export default function Home(){
 return <div data-testid="home-page">
  <section className="relative min-h-[640px] flex items-center overflow-hidden bg-slate-950 text-white"><img src="https://images.pexels.com/photos/3952137/pexels-photo-3952137.jpeg?auto=compress&dpr=1&h=750&w=1260" alt="" className="absolute inset-0 w-full h-full object-cover opacity-25"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/85 to-slate-950/30"/><div className="relative max-w-7xl mx-auto px-6 py-24 w-full"><div className="max-w-4xl"><p className="text-cyan-300 font-semibold uppercase tracking-wide text-sm">GASI · Grupo de Asistencia Sanitaria Integral</p><h1 className="text-4xl sm:text-5xl lg:text-7xl font-bold mt-4 leading-tight">Servicios sanitarios pensados para funcionar dentro de la empresa</h1><p className="text-xl text-slate-200 mt-6 max-w-3xl leading-relaxed">Configuramos cobertura sanitaria, apoyo asistencial y formación alrededor de la realidad de cada centro: actividad, turnos, trabajadores y necesidades operativas.</p><div className="flex flex-col sm:flex-row gap-4 mt-9"><Link to="/contacto" className="inline-flex items-center justify-center bg-white text-[#005EB8] font-bold px-7 py-3 rounded-xl">Solicitar información <ArrowRight className="ml-2 w-5 h-5"/></Link><Link to="/servicios" className="inline-flex items-center justify-center border border-white/50 hover:bg-white/10 font-semibold px-7 py-3 rounded-xl">Ver servicios</Link></div></div></div></section>
  <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-6"><div className="max-w-3xl"><p className="text-[#005EB8] font-semibold uppercase tracking-wide text-sm">Qué hacemos</p><h2 className="text-3xl lg:text-5xl font-bold text-slate-900 mt-2">Una cobertura distinta según el centro</h2><p className="text-lg text-slate-600 mt-5">No vendemos una plantilla idéntica para todas las empresas. La propuesta define qué recursos tienen sentido, cómo se coordinan y qué queda fuera del servicio.</p></div><div className="grid lg:grid-cols-3 gap-7 mt-12">{services.map(({title,text,link,image,icon:Icon})=><Link to={link} key={title} className="group rounded-3xl overflow-hidden border bg-white shadow-sm hover:shadow-xl transition-all"><div className="h-56 overflow-hidden"><img src={image} alt="" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"/></div><div className="p-7"><div className="w-11 h-11 rounded-xl bg-[#005EB8]/10 text-[#005EB8] flex items-center justify-center"><Icon className="w-6 h-6"/></div><h3 className="text-2xl font-bold text-slate-900 mt-5">{title}</h3><p className="text-slate-600 mt-3 leading-relaxed">{text}</p><span className="inline-flex items-center text-[#005EB8] font-bold mt-5">Más información <ArrowRight className="ml-2 w-4 h-4"/></span></div></Link>)}</div></div></section>
  <section className="py-20 bg-[#F3F7FB]"><div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-[.9fr_1.1fr] gap-12 items-center"><div><p className="text-[#005EB8] font-semibold uppercase tracking-wide text-sm">Cómo trabajamos</p><h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mt-2">Primero entendemos la operación</h2><p className="text-lg text-slate-600 mt-5">Antes de hablar de profesionales o precios, revisamos el centro, los turnos, el perfil de actividad y la capacidad que realmente necesita el cliente.</p><Link to="/servicios" className="inline-flex items-center mt-7 text-[#005EB8] font-bold">Ver el enfoque completo <ArrowRight className="ml-2 w-5 h-5"/></Link></div><div className="grid gap-5">{strengths.map(({icon:Icon,title,text})=><div key={title} className="rounded-2xl bg-white border p-6 flex gap-5"><div className="w-12 h-12 shrink-0 rounded-xl bg-[#005EB8]/10 text-[#005EB8] flex items-center justify-center"><Icon className="w-6 h-6"/></div><div><h3 className="text-xl font-bold text-slate-900">{title}</h3><p className="text-slate-600 mt-2">{text}</p></div></div>)}</div></div></section>
  <section className="py-20 bg-slate-950 text-white"><div className="max-w-4xl mx-auto px-6 text-center"><h2 className="text-3xl lg:text-5xl font-bold">Cuéntenos cómo funciona su centro</h2><p className="text-xl text-slate-300 mt-5">A partir de ahí podemos plantear una cobertura sanitaria coherente con la operación real.</p><Link to="/contacto" className="inline-flex items-center mt-8 bg-cyan-300 text-slate-950 font-bold px-7 py-3 rounded-xl">Hablar con coordinación <ArrowRight className="ml-2 w-5 h-5"/></Link></div></section>
 </div>;
}
