import React,{useCallback,useEffect,useState}from'react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';
const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
export default function InternalWorkstations(){
 const{token,isMaster}=useInternalPrototypeAuth(),[items,setItems]=useState([]),[form,setForm]=useState({id:'',center:'',label:''}),[credential,setCredential]=useState(''),[message,setMessage]=useState('');
 const headers=useCallback((json=false)=>({...json?{'Content-Type':'application/json'}:{},Authorization:`Bearer ${token}`}),[token]);
 const load=useCallback(async()=>{if(!token||!isMaster)return;try{const r=await fetch(`${apiRoot()}/api/internal-clinical/workstations`,{headers:headers(),cache:'no-store'});if(r.ok)setItems(await r.json());else setMessage(`Inventario rechazado (HTTP ${r.status}).`);}catch(_){setMessage('No se pudo cargar el inventario.');}},[token,isMaster,headers]);
 useEffect(()=>{load();},[load]);
 if(!isMaster)return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-4xl mx-auto px-4"><h1 className="text-3xl font-bold">Puestos de centro</h1><p role="alert" className="mt-4 text-amber-200">Gestión reservada a la cuenta maestra.</p></div></main>;
 const create=async e=>{e.preventDefault();setCredential('');setMessage('');try{const r=await fetch(`${apiRoot()}/api/internal-clinical/workstations`,{method:'POST',headers:headers(true),body:JSON.stringify(form)}),data=await r.json();if(!r.ok){setMessage(data.detail||`Alta rechazada (HTTP ${r.status}).`);return;}setCredential(data.workstation_credential||'');setForm({id:'',center:'',label:''});await load();}catch(_){setMessage('No se pudo registrar el puesto.');}};
 const toggle=async item=>{setMessage('');try{const action=item.active?'revoke':'activate',r=await fetch(`${apiRoot()}/api/internal-clinical/workstations/${encodeURIComponent(item.id)}/${action}`,{method:'POST',headers:headers()});if(!r.ok){setMessage(`Cambio rechazado (HTTP ${r.status}).`);return;}await load();}catch(_){setMessage('No se pudo cambiar el estado del puesto.');}};
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10" data-testid="internal-workstations"><div className="max-w-4xl mx-auto px-4 space-y-6"><header><h1 className="text-3xl font-bold">Puestos de centro</h1><p className="text-slate-400 mt-2">Alta, revocación y reactivación de los ordenadores autorizados para fichaje.</p></header><form onSubmit={create} className="rounded-2xl border border-slate-800 bg-slate-900 p-6 grid sm:grid-cols-3 gap-3"><input required aria-label="ID del puesto" placeholder="ID del puesto" value={form.id} onChange={e=>setForm({...form,id:e.target.value})} className="rounded-lg bg-slate-950 border border-slate-700 p-3"/><input required aria-label="Centro" placeholder="Centro" value={form.center} onChange={e=>setForm({...form,center:e.target.value})} className="rounded-lg bg-slate-950 border border-slate-700 p-3"/><input required aria-label="Etiqueta" placeholder="Etiqueta" value={form.label} onChange={e=>setForm({...form,label:e.target.value})} className="rounded-lg bg-slate-950 border border-slate-700 p-3"/><button className="sm:col-span-3 rounded-lg bg-cyan-400 text-slate-950 font-semibold px-4 py-2">Registrar puesto</button></form>{credential&&<section role="status" className="rounded-xl border border-amber-400/50 bg-amber-400/10 p-4"><p className="font-semibold text-amber-200">Credencial mostrada una sola vez</p><code className="block mt-2 break-all select-all">{credential}</code><p className="text-sm text-amber-100/80 mt-2">Configúrala en el puesto autorizado y no la guardes en notas compartidas.</p></section>}{message&&<p role="status">{message}</p>}<section className="space-y-2">{items.map(item=><div key={item.id} className="rounded-xl border border-slate-800 bg-slate-900 p-4 flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{item.label}</p><p className="text-sm text-slate-400">{item.center} · {item.id}</p><p className={item.active?'text-emerald-300 text-sm':'text-red-300 text-sm'}>{item.active?'Activo':'Revocado'}</p></div><button onClick={()=>toggle(item)} className="rounded-lg border border-slate-600 px-4 py-2">{item.active?'Revocar':'Reactivar'}</button></div>)}</section></div></main>;
}
