import React,{useState}from'react';
import{useNavigate}from'react-router-dom';
import{LockKeyhole,ShieldCheck}from'lucide-react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';
export default function InternalAccess(){
 const navigate=useNavigate(),{session,lastError,sessionChecking,signIn,signOut,changePassword}=useInternalPrototypeAuth();
 const[workerId,setWorkerId]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[changeMessage,setChangeMessage]=useState('');
 const submit=async e=>{e.preventDefault();if(await signIn(workerId.trim(),password)){setChangeMessage('');}};
 const submitPasswordChange=async e=>{e.preventDefault();setChangeMessage('');if(newPassword.length<12){setChangeMessage('La nueva contraseña debe tener al menos 12 caracteres.');return;}if(newPassword!==confirmPassword){setChangeMessage('Las nuevas contraseñas no coinciden.');return;}const result=await changePassword(password,newPassword);if(!result.ok){setChangeMessage(result.error);return;}setPassword('');setNewPassword('');setConfirmPassword('');setChangeMessage('Contraseña actualizada. Vuelve a iniciar sesión.');};
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-12"><div className="max-w-md mx-auto px-4">
  <header className="mb-8"><div className="flex items-center gap-2 text-cyan-300 text-sm font-semibold"><ShieldCheck className="w-4 h-4"/>GASI · Zona interna</div><h1 className="text-3xl font-bold mt-2">Acceso profesional</h1><p className="text-slate-400 mt-2">Acceso individual. Las acciones quedan vinculadas a la identidad autenticada.</p></header>
  {session?(session.mustChangePassword?<section className="rounded-2xl border border-amber-400/40 bg-slate-900 p-6"><p className="text-sm text-amber-300">Primer acceso</p><h2 className="text-xl font-bold mt-1">{session.displayName}</h2><p className="text-slate-400 mt-2">Debes sustituir la contraseña temporal antes de acceder a cualquier función operativa.</p><form onSubmit={submitPasswordChange} className="mt-5"><label className="block text-sm">Nueva contraseña<input type="password" autoComplete="new-password" required minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="w-full mt-1 rounded-lg bg-slate-950 border border-slate-700 px-3 py-2"/></label><label className="block mt-4 text-sm">Repetir nueva contraseña<input type="password" autoComplete="new-password" required minLength={12} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} className="w-full mt-1 rounded-lg bg-slate-950 border border-slate-700 px-3 py-2"/></label>{changeMessage&&<p role="status" aria-live="polite" className="mt-4 text-sm text-amber-200">{changeMessage}</p>}<button disabled={sessionChecking} className="mt-5 w-full rounded-lg bg-amber-300 disabled:opacity-50 text-slate-950 font-semibold px-4 py-2">{sessionChecking?'Actualizando…':'Cambiar contraseña y cerrar sesión'}</button></form><button type="button" onClick={signOut} className="mt-3 w-full rounded-lg border border-slate-700 px-4 py-2">Cancelar y cerrar sesión</button></section>:<section className="rounded-2xl border border-emerald-500/30 bg-slate-900 p-6"><p className="text-sm text-emerald-300">Sesión activa</p><h2 className="text-xl font-bold mt-1">{session.displayName}</h2><p className="text-slate-400">{session.roleLabel}</p><button type="button" onClick={()=>navigate('/interno/clinica')} className="mt-5 w-full rounded-lg bg-cyan-400 text-slate-950 font-semibold px-4 py-2">Entrar</button><button type="button" onClick={signOut} className="mt-3 w-full rounded-lg border border-slate-700 px-4 py-2">Cerrar sesión</button></section>):
  <form onSubmit={submit} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><LockKeyhole className="w-7 h-7 text-cyan-300"/><label className="block mt-5 text-sm">Identificador profesional<input autoComplete="username" required value={workerId} onChange={e=>setWorkerId(e.target.value)} className="w-full mt-1 rounded-lg bg-slate-950 border border-slate-700 px-3 py-2"/></label><label className="block mt-4 text-sm">Contraseña<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="w-full mt-1 rounded-lg bg-slate-950 border border-slate-700 px-3 py-2"/></label>{lastError&&<p role="alert" className="mt-4 text-sm text-rose-300">{lastError}</p>}<button disabled={sessionChecking} className="mt-5 w-full rounded-lg bg-cyan-400 disabled:opacity-50 text-slate-950 font-semibold px-4 py-2">{sessionChecking?'Validando…':'Acceder'}</button></form>}
 </div></main>;
}