import React,{useEffect,useMemo,useState}from'react';
import{Link,useNavigate}from'react-router-dom';
import{HeartPulse,LogOut,Plus,RefreshCw,ShieldCheck,Stethoscope,UserCog}from'lucide-react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';
import{createInternalClinicalApi}from'@/lib/internalClinicalApi';
import{loadAuthoritativeEpisodes,partitionAuthoritativeEpisodes}from'@/lib/internalClinicalAuthority';

const ROLES={nurse:{label:'Enfermería',icon:HeartPulse},physician:{label:'Facultativo',icon:Stethoscope},admin:{label:'Administración / Coordinación',icon:UserCog},psychologist:{label:'Psicología',icon:HeartPulse},physiotherapist:{label:'Fisioterapia',icon:HeartPulse}};
const badge=s=>({ABIERTO:'bg-amber-100 text-amber-900',RESPONDIDO:'bg-blue-100 text-blue-900',CERRADO:'bg-emerald-100 text-emerald-900'}[s]||'bg-slate-200 text-slate-900');

export default function InternalClinicalPrototype(){
 const navigate=useNavigate();
 const{session,token,signOut,canManageWorkers}=useInternalPrototypeAuth();
 const api=useMemo(()=>token?createInternalClinicalApi({token}):null,[token]);
 const[episodes,setEpisodes]=useState([]),[state,setState]=useState('LOADING'),[error,setError]=useState('');
 const RoleIcon=ROLES[session?.role]?.icon||ShieldCheck;
 const load=async()=>{if(!api)return;setState('LOADING');setError('');const r=await loadAuthoritativeEpisodes(api);if(!r.ok){setEpisodes([]);setError(r.errorCode);setState('ERROR');return;}setEpisodes(r.episodes);setState('READY');};
 useEffect(()=>{load();},[api]);
 if(!session||!token)return null;
 const{pending,closed}=partitionAuthoritativeEpisodes(episodes);
 const canCreate=['nurse','psychologist','physiotherapist'].includes(session.role);
 const logout=async()=>{await signOut();navigate('/interno/acceso',{replace:true});};
 const Card=({episode})=><Link to={`/interno/prototipo-clinico/caso/${encodeURIComponent(episode.id)}`} className="block rounded-xl border border-slate-800 bg-slate-900 p-4 hover:border-cyan-500 focus:outline-none focus:ring-2 focus:ring-cyan-400"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{episode.id}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${badge(episode.status)}`}>{episode.status}</span></div><div className="mt-2 text-sm text-slate-400"><span>{episode.center||'Centro no indicado'}</span>{episode.discipline==='nursing'&&<span> · Nivel {episode.level}</span>}</div>{session.role!=='admin'&&<p className="mt-3 line-clamp-2 text-sm">{episode.summary||'Sin resumen'}</p>}{session.role==='admin'&&<p className="mt-3 text-sm text-slate-500">Vista administrativa: metadatos operativos únicamente.</p>}</Link>;
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-8"><div className="mx-auto max-w-6xl px-4"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-800 pb-5"><div><p className="text-sm text-cyan-300">GASI · Zona interna</p><h1 className="mt-1 text-3xl font-bold">Canal asistencial</h1><div className="mt-2 flex items-center gap-2 text-sm text-slate-400"><RoleIcon className="h-4 w-4"/><span>{session.displayName} · {ROLES[session.role]?.label||session.roleLabel}</span></div></div><div className="flex flex-wrap gap-2">{canCreate&&<Link to="/interno/prototipo-clinico/nuevo" className="inline-flex items-center gap-2 rounded-lg bg-cyan-300 px-4 py-2 font-semibold text-slate-950"><Plus className="h-4 w-4"/>Nuevo episodio</Link>}{canManageWorkers&&<Link to="/interno/trabajadores" className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Usuarios y accesos</Link>}<button onClick={logout} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-4 py-2 text-sm"><LogOut className="h-4 w-4"/>Salir</button></div></header><section className="mt-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Episodios visibles</h2><p className="mt-1 text-sm text-slate-400">El servidor decide qué recursos son visibles para esta identidad y sus centros asignados.</p></div><button onClick={load} disabled={state==='LOADING'} className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm disabled:opacity-50"><RefreshCw className="h-4 w-4"/>Actualizar</button></div>{state==='LOADING'&&<p role="status" className="mt-6 text-slate-400">Cargando desde la autoridad clínica…</p>}{state==='ERROR'&&<div role="alert" className="mt-6 rounded-xl border border-red-500/40 bg-red-500/10 p-4"><strong>No se muestran datos locales de sustitución.</strong><p className="mt-1 text-sm">La autoridad clínica no está disponible. Código: {error}</p></div>}{state==='READY'&&<><h3 className="mt-6 font-semibold">Pendientes ({pending.length})</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{pending.map(e=><Card key={e.id} episode={e}/>)}{pending.length===0&&<p className="text-sm text-slate-500">No hay episodios pendientes visibles.</p>}</div><details className="mt-7"><summary className="cursor-pointer font-semibold">Cerrados ({closed.length})</summary><div className="mt-3 grid gap-3 md:grid-cols-2">{closed.map(e=><Card key={e.id} episode={e}/>)}{closed.length===0&&<p className="text-sm text-slate-500">No hay episodios cerrados visibles.</p>}</div></details></>}</section></div></main>;
}
