import React,{useCallback,useEffect,useState}from'react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';
const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
export const effectiveAttendance=(events=[])=>{const corrections=new Map();for(const e of events){if(e.event_type==='CORRECTION'&&e.related_event_seq!=null&&!corrections.has(Number(e.related_event_seq)))corrections.set(Number(e.related_event_seq),e);}return events.filter(e=>e.event_type!=='CORRECTION').map(e=>{const correction=corrections.get(Number(e.seq)),m=correction?.metadata||{};return correction?{...e,effective_event_type:m.corrected_event_type||e.event_type,effective_occurred_at:m.corrected_occurred_at||e.occurred_at,correction}:{...e,effective_event_type:e.event_type,effective_occurred_at:e.occurred_at,correction:null};});};
export default function InternalAttendance(){
 const{session,token}=useInternalPrototypeAuth(),[events,setEvents]=useState([]),[state,setState]=useState('idle'),[message,setMessage]=useState('');
 const workstationHint=localStorage.getItem('gasi_workstation_id')||'';
 const headers=useCallback(()=>({Authorization:`Bearer ${token}`}),[token]);
 const load=useCallback(async()=>{if(!token)return;try{const r=await fetch(`${apiRoot()}/api/internal-clinical/attendance`,{headers:headers(),cache:'no-store'});if(r.ok)setEvents(await r.json());}catch(_){}},[token,headers]);
 useEffect(()=>{load();},[load]);
 const clock=async(action)=>{setState('busy');setMessage('');try{const r=await fetch(`${apiRoot()}/api/internal-clinical/attendance/${action}`,{method:'POST',headers:headers(),credentials:'include'});const data=await r.json().catch(()=>({}));if(!r.ok){setMessage(data.detail==='workstation_binding_required'?'Este navegador no está vinculado a un puesto autorizado.':data.detail==='mobile_workstation_client_denied'?'El fichaje no está permitido desde un cliente móvil.':data.detail||`Fichaje rechazado (HTTP ${r.status}).`);return;}setMessage(action==='clock-in'?'Entrada registrada.':'Salida registrada.');await load();}catch(_){setMessage('No se pudo conectar con el servicio de fichaje.');}finally{setState('idle');}};
 if(!session)return null;
 if(session.role==='admin')return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-3xl mx-auto px-4"><h1 className="text-3xl font-bold">Fichaje</h1><p role="alert" className="mt-4 text-amber-200">La cuenta administrativa no puede fichar como profesional.</p></div></main>;
 const effective=effectiveAttendance(events);
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10" data-testid="internal-attendance"><div className="max-w-3xl mx-auto px-4 space-y-6"><header><h1 className="text-3xl font-bold">Fichaje</h1><p className="text-slate-400 mt-2">Entrada y salida del turno desde el ordenador vinculado del centro.</p>{workstationHint&&<p className="text-xs text-slate-500 mt-2">Puesto configurado: {workstationHint}</p>}</header><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6 space-y-4"><p className="text-sm text-slate-300">La identidad del puesto se valida mediante una credencial protegida del navegador. No se introduce ni se muestra durante el fichaje.</p><div className="flex gap-3"><button disabled={state==='busy'} onClick={()=>clock('clock-in')} className="rounded-lg bg-cyan-400 text-slate-950 font-semibold px-4 py-2 disabled:opacity-50">Registrar entrada</button><button disabled={state==='busy'} onClick={()=>clock('clock-out')} className="rounded-lg border border-cyan-400 px-4 py-2 disabled:opacity-50">Registrar salida</button></div>{message&&<p role="status" className="text-sm text-cyan-100">{message}</p>}</section><section><h2 className="text-xl font-semibold mb-3">Mis últimos fichajes</h2><div className="space-y-2">{effective.length?effective.map(e=><div key={e.seq} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div><span className="font-medium">{e.effective_event_type==='CLOCK_IN'?'Entrada':'Salida'}</span><span className="text-slate-400 ml-3">{new Date(e.effective_occurred_at).toLocaleString()}</span><span className="text-slate-500 ml-3">{e.center}</span>{e.correction&&<span className="text-amber-300 ml-3 text-sm">Corregido</span>}</div>{e.correction&&<p className="mt-2 text-xs text-slate-500">Original: {e.event_type==='CLOCK_IN'?'Entrada':'Salida'} · {new Date(e.occurred_at).toLocaleString()} · Motivo: {e.correction.reason||'sin detalle'}</p>}</div>):<p className="text-slate-400">Sin fichajes registrados.</p>}</div></section></div></main>;
}
