import React,{useCallback,useEffect,useMemo,useState}from'react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';
import{effectiveAttendance}from'@/pages/InternalAttendance';

const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
const localInputValue=iso=>{const d=new Date(iso);if(Number.isNaN(d.getTime()))return'';const off=d.getTimezoneOffset()*60000;return new Date(d.getTime()-off).toISOString().slice(0,16);};

export default function InternalAttendanceAdmin(){
 const{token,isMaster}=useInternalPrototypeAuth(),[events,setEvents]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState({event_type:'CLOCK_IN',occurred_at:'',reason:''}),[message,setMessage]=useState('');
 const headers=useCallback((json=false)=>({...json?{'Content-Type':'application/json'}:{},Authorization:`Bearer ${token}`}),[token]);
 const load=useCallback(async()=>{if(!token||!isMaster)return;try{const r=await fetch(`${apiRoot()}/api/internal-clinical/attendance?limit=250`,{headers:headers(),cache:'no-store'});if(r.ok)setEvents(await r.json());else setMessage(`Historial rechazado (HTTP ${r.status}).`);}catch(_){setMessage('No se pudo cargar el historial de fichajes.');}},[token,isMaster,headers]);
 useEffect(()=>{load();},[load]);
 const effective=useMemo(()=>effectiveAttendance(events),[events]);
 if(!isMaster)return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-5xl mx-auto px-4"><h1 className="text-3xl font-bold">Control de fichajes</h1><p role="alert" className="mt-4 text-amber-200">Consulta global y correcciones reservadas a la cuenta maestra.</p></div></main>;
 const edit=e=>{setEditing(e.seq);setForm({event_type:e.effective_event_type,occurred_at:localInputValue(e.effective_occurred_at),reason:''});setMessage('');};
 const cancel=()=>{setEditing(null);setForm({event_type:'CLOCK_IN',occurred_at:'',reason:''});};
 const correct=async e=>{e.preventDefault();if(!editing)return;setMessage('');try{const corrected=new Date(form.occurred_at);if(Number.isNaN(corrected.getTime())){setMessage('Fecha u hora no válida.');return;}const r=await fetch(`${apiRoot()}/api/internal-clinical/attendance/${editing}/correct`,{method:'POST',headers:headers(true),body:JSON.stringify({corrected_event_type:form.event_type,corrected_occurred_at:corrected.toISOString(),reason:form.reason})}),data=await r.json().catch(()=>({}));if(!r.ok){setMessage(data.detail||`Corrección rechazada (HTTP ${r.status}).`);return;}cancel();setMessage('Corrección registrada sin modificar el evento original.');await load();}catch(_){setMessage('No se pudo registrar la corrección.');}};
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10" data-testid="internal-attendance-admin"><div className="max-w-5xl mx-auto px-4 space-y-6"><header><h1 className="text-3xl font-bold">Control de fichajes</h1><p className="text-slate-400 mt-2">Historial global. Las correcciones se añaden como eventos auditables y conservan el original.</p></header>{message&&<p role="status" className="rounded-lg border border-slate-700 p-3">{message}</p>}{editing&&<form onSubmit={correct} className="rounded-2xl border border-amber-400/40 bg-amber-400/10 p-5 grid sm:grid-cols-3 gap-3"><select aria-label="Tipo corregido" value={form.event_type} onChange={e=>setForm({...form,event_type:e.target.value})} className="rounded-lg bg-slate-950 border border-slate-700 p-3"><option value="CLOCK_IN">Entrada</option><option value="CLOCK_OUT">Salida</option></select><input required aria-label="Fecha y hora corregidas" type="datetime-local" value={form.occurred_at} onChange={e=>setForm({...form,occurred_at:e.target.value})} className="rounded-lg bg-slate-950 border border-slate-700 p-3"/><input required aria-label="Motivo de la corrección" placeholder="Motivo" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} className="rounded-lg bg-slate-950 border border-slate-700 p-3"/><div className="sm:col-span-3 flex gap-3"><button className="rounded-lg bg-amber-300 text-slate-950 font-semibold px-4 py-2">Registrar corrección</button><button type="button" onClick={cancel} className="rounded-lg border border-slate-600 px-4 py-2">Cancelar</button></div></form>}<section className="space-y-2">{effective.length?effective.map(e=><article key={e.seq} className="rounded-xl border border-slate-800 bg-slate-900 p-4 flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{e.worker_id} · {e.effective_event_type==='CLOCK_IN'?'Entrada':'Salida'}{e.correction&&<span className="ml-2 text-sm text-amber-300">Corregido</span>}</p><p className="text-sm text-slate-400">{new Date(e.effective_occurred_at).toLocaleString()} · {e.center} · {e.workstation_id}</p>{e.correction&&<p className="text-xs text-slate-500 mt-1">Original: {new Date(e.occurred_at).toLocaleString()} · Motivo: {e.correction.reason||'sin detalle'}</p>}</div><button type="button" onClick={()=>edit(e)} className="rounded-lg border border-slate-600 px-4 py-2 self-start">Corregir</button></article>):<p className="text-slate-400">Sin fichajes registrados.</p>}</section></div></main>;
}
