import React,{useMemo,useState}from'react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';

const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
const CONFIRM='RESTAURAR';

export default function InternalRecovery(){
 const{token,isMaster}=useInternalPrototypeAuth();
 const[busy,setBusy]=useState('');
 const[message,setMessage]=useState('');
 const[snapshot,setSnapshot]=useState(null);
 const[fileName,setFileName]=useState('');
 const[confirm,setConfirm]=useState('');
 const summary=useMemo(()=>snapshot?{
  version:snapshot.schema_version,
  episodes:Array.isArray(snapshot.episodes)?snapshot.episodes.length:0,
  workers:Array.isArray(snapshot.workers)?snapshot.workers.length:0,
  audit:Array.isArray(snapshot.audit)?snapshot.audit.length:0,
  workstations:Array.isArray(snapshot.workstations)?snapshot.workstations.length:0,
  attendance:Array.isArray(snapshot.attendance)?snapshot.attendance.length:0,
  signed:typeof snapshot.snapshot_signature==='string'&&snapshot.snapshot_signature.length===64
 }:null,[snapshot]);
 if(!isMaster)return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-4xl mx-auto px-4"><h1 className="text-3xl font-bold">Recuperación</h1><p role="alert" className="mt-4 text-amber-200">Operación reservada a la cuenta maestra.</p></div></main>;
 const headers=json=>({...json?{'Content-Type':'application/json'}:{},Authorization:`Bearer ${token}`});
 const exportSnapshot=async()=>{if(busy)return;setBusy('export');setMessage('');try{const r=await fetch(`${apiRoot()}/api/internal-clinical/recovery/snapshot`,{headers:headers(false),cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok){setMessage(data.detail||`Exportación rechazada (HTTP ${r.status}).`);return;}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a'),stamp=new Date().toISOString().replace(/[:.]/g,'-');a.href=url;a.download=`gasi-recovery-${stamp}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMessage('Snapshot firmado exportado. Guárdalo en un repositorio seguro.');}catch(_){setMessage('No se pudo exportar el snapshot.');}finally{setBusy('');}};
 const chooseFile=async e=>{setMessage('');setConfirm('');const file=e.target.files?.[0];if(!file){setSnapshot(null);setFileName('');return;}try{const text=await file.text(),parsed=JSON.parse(text);setSnapshot(parsed);setFileName(file.name);if(parsed?.schema_version!==2||typeof parsed?.snapshot_signature!=='string')setMessage('El archivo no parece un snapshot firmado de recovery V2.');}catch(_){setSnapshot(null);setFileName(file.name);setMessage('El archivo no contiene JSON válido.');}};
 const restore=async()=>{if(busy||!snapshot||confirm!==CONFIRM)return;setBusy('restore');setMessage('');try{const r=await fetch(`${apiRoot()}/api/internal-clinical/recovery/restore`,{method:'POST',headers:headers(true),body:JSON.stringify(snapshot)}),data=await r.json().catch(()=>({}));if(!r.ok){setMessage(data.detail||`Restauración rechazada (HTTP ${r.status}).`);return;}setMessage(`Restauración completada: ${data.episodes||0} episodios, ${data.workers||0} usuarios, ${data.attendance||0} eventos de fichaje.`);setSnapshot(null);setFileName('');setConfirm('');}catch(_){setMessage('No se pudo completar la restauración.');}finally{setBusy('');}};
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10" data-testid="internal-recovery"><div className="max-w-4xl mx-auto px-4 space-y-6"><header><h1 className="text-3xl font-bold">Backup y recuperación</h1><p className="mt-2 text-slate-400">Exporta snapshots firmados y restaura únicamente copias generadas por esta instalación.</p></header><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Exportar snapshot</h2><p className="mt-2 text-sm text-slate-400">Incluye episodios, usuarios, auditoría, puestos y fichajes. La copia contiene hashes y datos clínicos: trátala como información sensible.</p><button type="button" disabled={Boolean(busy)} onClick={exportSnapshot} className="mt-4 rounded-lg bg-cyan-400 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{busy==='export'?'Exportando…':'Descargar snapshot firmado'}</button></section><section className="rounded-2xl border border-red-500/30 bg-slate-900 p-6"><h2 className="text-xl font-semibold text-red-200">Restaurar snapshot</h2><p className="mt-2 text-sm text-slate-400">La restauración sustituye el estado actual completo. El servidor verifica estructura, referencias, procedencia y firma antes de modificar datos.</p><label className="mt-4 block text-sm">Archivo de snapshot<input type="file" accept="application/json,.json" disabled={Boolean(busy)} onChange={chooseFile} className="mt-2 block w-full rounded-lg border border-slate-700 bg-slate-950 p-3"/></label>{summary&&<div className="mt-4 rounded-xl border border-slate-700 bg-slate-950 p-4 text-sm"><p><b>{fileName}</b></p><p className="mt-2">Esquema V{summary.version} · {summary.episodes} episodios · {summary.workers} usuarios · {summary.audit} eventos de auditoría · {summary.workstations} puestos · {summary.attendance} eventos de fichaje</p><p className={summary.signed?'mt-2 text-emerald-300':'mt-2 text-red-300'}>{summary.signed?'Firma presente':'Firma ausente o inválida en formato'}</p></div>}{snapshot&&<label className="mt-4 block text-sm">Escribe <b>{CONFIRM}</b> para habilitar la restauración<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off" className="mt-2 w-full rounded-lg border border-red-500/40 bg-slate-950 p-3"/></label>}<button type="button" disabled={Boolean(busy)||!summary?.signed||confirm!==CONFIRM} onClick={restore} className="mt-4 rounded-lg border border-red-400 px-4 py-2 font-semibold text-red-100 disabled:opacity-40">{busy==='restore'?'Restaurando…':'Restaurar estado completo'}</button></section>{message&&<p role="status" aria-live="polite" className="rounded-lg border border-slate-700 bg-slate-900 p-4">{message}</p>}</div></main>;
}
