import React,{useCallback,useEffect,useState}from'react';
import{ArrowLeft,Clock3,Copy,MonitorSmartphone,RefreshCcw,ShieldAlert}from'lucide-react';
import{useNavigate}from'react-router-dom';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';

const headers=(token,json=false)=>({...json?{'Content-Type':'application/json'}:{},Authorization:`Bearer ${token}`});

export default function InternalTimeclockAdmin(){
 const nav=useNavigate(),{session,token,isMaster,canManageWorkers}=useInternalPrototypeAuth();
 const[devices,setDevices]=useState([]),[events,setEvents]=useState([]),[form,setForm]=useState({center:'',label:''}),[activation,setActivation]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const allowed=Boolean(session&&(isMaster||canManageWorkers));
 const load=useCallback(async()=>{if(!allowed)return;setBusy(true);setMessage('');try{
  const reqs=[fetch('/api/internal-clinical/timeclock/events',{headers:headers(token),cache:'no-store'})];
  if(isMaster)reqs.push(fetch('/api/internal-clinical/timeclock/devices',{headers:headers(token),cache:'no-store'}));
  const responses=await Promise.all(reqs);if(!responses[0].ok)throw new Error('No se han podido cargar los fichajes.');
  setEvents(await responses[0].json());
  if(isMaster){if(!responses[1].ok)throw new Error('No se han podido cargar los terminales.');setDevices(await responses[1].json());}
 }catch(e){setMessage(e.message||'No se ha podido cargar el control horario.');}finally{setBusy(false);}},[allowed,isMaster,token]);
 useEffect(()=>{load();},[load]);
 if(!allowed)return <main className="min-h-screen bg-slate-950 text-slate-100 p-10"><h1 className="text-2xl font-bold">Acceso restringido</h1><p className="mt-2 text-slate-400">El control horario requiere permisos de gestión.</p></main>;

 const create=async e=>{e.preventDefault();setBusy(true);setActivation(null);setMessage('');try{const r=await fetch('/api/internal-clinical/timeclock/devices',{method:'POST',headers:headers(token,true),body:JSON.stringify(form)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||'No se ha podido crear el terminal.');setActivation(d);setForm({center:'',label:''});await load();}catch(e){setMessage(e.message);}finally{setBusy(false);}};
 const revoke=async id=>{if(!window.confirm('¿Revocar este terminal? Dejará de poder fichar inmediatamente.'))return;setBusy(true);try{const r=await fetch(`/api/internal-clinical/timeclock/devices/${encodeURIComponent(id)}/revoke`,{method:'POST',headers:headers(token)});if(!r.ok)throw new Error('No se ha podido revocar.');await load();}catch(e){setMessage(e.message);}finally{setBusy(false);}};
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-7xl mx-auto px-4">
  <header className="flex items-start justify-between gap-4"><div><p className="text-cyan-300 text-sm font-semibold">GASI · Zona interna</p><h1 className="text-3xl font-bold mt-1">Control horario</h1><p className="text-slate-400 mt-2">Los fichajes se aceptan únicamente desde terminales registrados en el centro.</p></div><button onClick={()=>nav('/interno/clinica')} aria-label="Volver"><ArrowLeft/></button></header>
  {message&&<p role="alert" className="mt-5 rounded-xl border border-rose-500/30 bg-rose-950/30 p-4 text-rose-200">{message}</p>}
  {isMaster&&<section className="grid lg:grid-cols-[360px_1fr] gap-6 mt-8">
   <form onSubmit={create} className="rounded-2xl bg-slate-900 border border-slate-800 p-5"><h2 className="font-bold flex items-center gap-2"><MonitorSmartphone className="w-5 h-5"/>Nuevo terminal</h2><label className="block mt-4 text-sm">Centro<input required value={form.center} onChange={e=>setForm({...form,center:e.target.value})} className="w-full mt-1 p-2 rounded bg-slate-950 border border-slate-700"/></label><label className="block mt-3 text-sm">Nombre del terminal<input required value={form.label} onChange={e=>setForm({...form,label:e.target.value})} placeholder="Recepción · PC fichaje" className="w-full mt-1 p-2 rounded bg-slate-950 border border-slate-700"/></label><button disabled={busy} className="w-full mt-4 rounded bg-cyan-400 text-slate-950 font-bold p-2">Crear terminal</button></form>
   <div className="rounded-2xl bg-slate-900 border border-slate-800 p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Terminales registrados</h2><button onClick={load} aria-label="Actualizar"><RefreshCcw className="w-4 h-4"/></button></div><div className="mt-4 space-y-3">{devices.length===0?<p className="text-slate-500">No hay terminales registrados.</p>:devices.map(d=><div key={d.id} className="rounded-xl border border-slate-800 p-4 flex items-center justify-between gap-4"><div><b>{d.label}</b><p className="text-sm text-slate-400">{d.center} · {d.id}</p><p className="text-xs mt-1 text-slate-500">{d.active?'Activo':'Revocado'}{d.last_seen_at?` · Último uso ${new Date(d.last_seen_at).toLocaleString()}`:''}</p></div>{d.active&&<button onClick={()=>revoke(d.id)} disabled={busy} className="text-rose-300 text-sm">Revocar</button>}</div>)}</div></div>
  </section>}
  {activation&&<section className="mt-6 rounded-2xl border border-amber-400/30 bg-amber-950/20 p-5"><div className="flex items-start gap-3"><ShieldAlert className="w-5 h-5 text-amber-300 mt-1"/><div className="flex-1"><h2 className="font-bold text-amber-200">Código de activación de un solo uso</h2><p className="text-sm text-slate-300 mt-1">Activa físicamente el terminal en <code>/interno/fichaje/activar</code>. Después este código deja de servir.</p><div className="mt-3 grid sm:grid-cols-[1fr_auto] gap-2"><code className="bg-slate-950 rounded p-3 break-all">{activation.id} · {activation.activation_token}</code><button onClick={()=>navigator.clipboard?.writeText(`${activation.id}\n${activation.activation_token}`)} className="rounded border border-slate-700 px-3 flex items-center justify-center gap-2"><Copy className="w-4 h-4"/>Copiar</button></div></div></div></section>}
  <section className="mt-8 rounded-2xl bg-slate-900 border border-slate-800 p-5 overflow-x-auto"><div className="flex items-center justify-between"><h2 className="font-bold flex items-center gap-2"><Clock3 className="w-5 h-5"/>Últimos fichajes</h2><button onClick={load} className="text-sm text-cyan-300">Actualizar</button></div><table className="w-full min-w-[760px] text-sm mt-4"><thead><tr className="text-left text-slate-500 border-b border-slate-800"><th className="py-2">Hora</th><th>Trabajador</th><th>Centro</th><th>Tipo</th><th>Terminal</th></tr></thead><tbody>{events.map(e=><tr key={e.id} className="border-b border-slate-800/70"><td className="py-3">{new Date(e.occurred_at).toLocaleString()}</td><td className="font-mono text-xs">{e.worker_id}</td><td>{e.center}</td><td><span className={e.event_type==='IN'?'text-emerald-300':'text-amber-300'}>{e.event_type==='IN'?'Entrada':'Salida'}</span></td><td className="font-mono text-xs">{e.device_id}</td></tr>)}</tbody></table>{events.length===0&&<p className="text-slate-500 mt-4">Todavía no hay fichajes.</p>}</section>
 </div></main>;
}
