import React,{useCallback,useEffect,useMemo,useState}from'react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';

const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
const clean=(value)=>value==null?'—':String(value);

export default function InternalAudit(){
 const{token,isMaster}=useInternalPrototypeAuth(),[rows,setRows]=useState([]),[query,setQuery]=useState(''),[state,setState]=useState('loading'),[message,setMessage]=useState('');
 const headers=useCallback(()=>({Authorization:`Bearer ${token}`}),[token]);
 const load=useCallback(async()=>{if(!token||!isMaster)return;setState('loading');setMessage('');try{const r=await fetch(`${apiRoot()}/api/internal-clinical/audit?limit=500`,{headers:headers(),cache:'no-store'});const data=await r.json().catch(()=>[]);if(!r.ok){setMessage(`Auditoría rechazada (HTTP ${r.status}).`);setRows([]);return;}setRows(Array.isArray(data)?data:[]);}catch(_){setMessage('No se pudo cargar la auditoría.');setRows([]);}finally{setState('ready');}},[token,isMaster,headers]);
 useEffect(()=>{load();},[load]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(row=>[row.seq,row.actor_id,row.actor_role,row.action,row.episode_id,...Object.entries(row.metadata||{}).flat()].some(v=>String(v??'').toLowerCase().includes(q)));},[rows,query]);
 if(!isMaster)return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-6xl mx-auto px-4"><h1 className="text-3xl font-bold">Auditoría</h1><p role="alert" className="mt-4 text-amber-200">Consulta reservada a la cuenta maestra.</p></div></main>;
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10" data-testid="internal-audit"><div className="max-w-6xl mx-auto px-4 space-y-5"><header><h1 className="text-3xl font-bold">Auditoría interna</h1><p className="text-slate-400 mt-2">Eventos técnicos y operativos inmutables. El log no muestra narrativas clínicas.</p></header><div className="flex flex-wrap gap-3 items-center"><label className="flex-1 min-w-64 text-sm">Filtrar auditoría<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Actor, acción, episodio o metadato" className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 p-3"/></label><button type="button" disabled={state==='loading'} onClick={load} className="self-end rounded-lg border border-cyan-400 px-4 py-3 disabled:opacity-50">{state==='loading'?'Actualizando…':'Actualizar'}</button></div>{message&&<p role="status" aria-live="polite" className="rounded-lg border border-slate-700 p-3">{message}</p>}<section aria-busy={state==='loading'} className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[980px] text-sm"><thead className="bg-slate-900 text-slate-300"><tr><th className="p-3 text-left">Sec.</th><th className="p-3 text-left">Fecha</th><th className="p-3 text-left">Actor</th><th className="p-3 text-left">Acción</th><th className="p-3 text-left">Episodio</th><th className="p-3 text-left">Metadatos</th><th className="p-3 text-left">Hash</th></tr></thead><tbody>{filtered.map(row=><tr key={row.seq} className="border-t border-slate-800 align-top"><td className="p-3 font-mono">{row.seq}</td><td className="p-3 whitespace-nowrap">{new Date(row.at).toLocaleString()}</td><td className="p-3"><div>{clean(row.actor_id)}</div><div className="text-xs text-slate-500">{clean(row.actor_role)}</div></td><td className="p-3 font-medium">{clean(row.action)}</td><td className="p-3 font-mono text-xs">{clean(row.episode_id)}</td><td className="p-3"><dl className="space-y-1">{Object.entries(row.metadata||{}).map(([k,v])=><div key={k} className="flex gap-2"><dt className="text-slate-500">{k}</dt><dd className="break-all">{clean(v)}</dd></div>)}</dl></td><td className="p-3 font-mono text-xs break-all"><div title={row.event_hash}>{String(row.event_hash||'').slice(0,16)}…</div><div className="mt-1 text-slate-600" title={row.previous_hash}>prev {String(row.previous_hash||'').slice(0,10)}…</div></td></tr>)}</tbody></table>{state==='ready'&&!filtered.length&&<p className="p-5 text-slate-400">No hay eventos que coincidan.</p>}</section></div></main>;
}
