import React,{useCallback,useEffect,useState}from'react';
import{useInternalPrototypeAuth}from'@/contexts/InternalPrototypeAuthContext';
const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
export default function InternalAttendance(){
 const{session,token}=useInternalPrototypeAuth(),[credential,setCredential]=useState(''),[workstationId,setWorkstationId]=useState(()=>localStorage.getItem('gasi_workstation_id')||''),[events,setEvents]=useState([]),[state,setState]=useState('idle'),[message,setMessage]=useState('');
 const headers=useCallback((json=false)=>({...json?{'Content-Type':'application/json'}:{},Authorization:`Bearer ${token}`}),[token]);
 const load=useCallback(async()=>{if(!token)return;try{const r=await fetch(`${apiRoot()}/api/internal-clinical/attendance`,{headers:headers(),cache:'no-store'});if(r.ok)setEvents(await r.json());}catch(_){}},[token,headers]);
 useEffect(()=>{load();},[load]);
 const clock=async(action)=>{setState('busy');setMessage('');try{localStorage.setItem('gasi_workstation_id',workstationId);const r=await fetch(`${apiRoot()}/api/internal-clinical/attendance/${action}`,{method:'POST',headers:headers(true),body:JSON.stringify({workstation_id:workstationId,workstation_credential:credential})});const data=await r.json().catch(()=>({}));if(!r.ok){setMessage(data.detail||`Fichaje rechazado (HTTP ${r.status}).`);return;}setMessage(action==='clock-in'?'Entrada registrada.':'Salida registrada.');setCredential('');await load();}catch(_){setMessage('No se pudo conectar con el servicio de fichaje.');}finally{setState('idle');}};
 if(!session)return null;
 if(session.role==='admin')return <main className="min-h-screen bg-slate-950 text-slate-100 py-10"><div className="max-w-3xl mx-auto px-4"><h1 className="text-3xl font-bold">Fichaje</h1><p role="alert" className="mt-4 text-amber-200">La cuenta administrativa no puede fichar como profesional.</p></div></main>;
 return <main className="min-h-screen bg-slate-950 text-slate-100 py-10" data-testid="internal-attendance"><div className="max-w-3xl mx-auto px-4 space-y-6"><header><h1 className="text-3xl font-bold">Fichaje</h1><p className="text-slate-400 mt-2">Entrada y salida del turno desde el puesto registrado del centro.</p></header><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6 space-y-4"><label className="block">Puesto del centro<input aria-label="Identificador del puesto" value={workstationId} onChange={e=>setWorkstationId(e.target.value)} className="mt-2 w-full rounded-lg bg-slate-950 border border-slate-700 p-3"/></label><label className="block">Credencial del puesto<input aria-label="Credencial del puesto" type="password" autoComplete="off" value={credential} onChange={e=>setCredential(e.target.value)} className="mt-2 w-full rounded-lg bg-slate-950 border border-slate-700 p-3"/></label><div className="flex gap-3"><button disabled={state==='busy'||!workstationId||!credential} onClick={()=>clock('clock-in')} className="rounded-lg bg-cyan-400 text-slate-950 font-semibold px-4 py-2 disabled:opacity-50">Registrar entrada</button><button disabled={state==='busy'||!workstationId||!credential} onClick={()=>clock('clock-out')} className="rounded-lg border border-cyan-400 px-4 py-2 disabled:opacity-50">Registrar salida</button></div>{message&&<p role="status" className="text-sm text-cyan-100">{message}</p>}</section><section><h2 className="text-xl font-semibold mb-3">Mis últimos fichajes</h2><div className="space-y-2">{events.length?events.map(e=><div key={e.seq} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><span className="font-medium">{e.event_type==='CLOCK_IN'?'Entrada':e.event_type==='CLOCK_OUT'?'Salida':'Corrección'}</span><span className="text-slate-400 ml-3">{new Date(e.occurred_at).toLocaleString()}</span><span className="text-slate-500 ml-3">{e.center}</span></div>):<p className="text-slate-400">Sin fichajes registrados.</p>}</div></section></div></main>;
}
