import React from'react';
import{Link}from'react-router-dom';
import{ArrowRight,ClipboardCheck,HeartPulse,Network,ShieldCheck,Users}from'lucide-react';

const principles=[
 {icon:ClipboardCheck,title:'Alcance definido',text:'Cada propuesta deja claro qué servicio se presta, con qué profesionales y bajo qué condiciones.'},
 {icon:ShieldCheck,title:'Seguridad y trazabilidad',text:'Diseñamos accesos, registros y correcciones para un uso sanitario real, con responsabilidades diferenciadas.'},
 {icon:Network,title:'Coordinación',text:'La presencia en centro y el apoyo remoto se organizan como un mismo servicio cuando la configuración lo requiere.'},
 {icon:Users,title:'Adaptación operativa',text:'Partimos de turnos, actividad, distribución de trabajadores y necesidades del centro, no de un paquete estándar.'}
];

export default function QuienesSomos(){
 return <div data-testid="quienes-somos-page">
  <section className="bg-slate-950 text-white"><div className="max-w-7xl mx-auto px-6 py-20 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center"><div><p className="text-cyan-300 font-semibold uppercase tracking-wide text-sm">Quiénes somos</p><h1 className="text-4xl lg:text-6xl font-bold mt-3">GASI nace para integrar asistencia sanitaria en la operativa real de las empresas</h1><p className="text-xl text-slate-300 mt-6 leading-relaxed">Grupo de Asistencia Sanitaria Integral organiza servicios sanitarios B2B con un enfoque práctico: entender el centro, definir el recurso necesario y dejar claros los circuitos de actuación.</p><Link to="/contacto" className="inline-flex items-center mt-8 bg-white text-[#005EB8] font-bold px-6 py-3 rounded-xl">Hablar con GASI <ArrowRight className="ml-2 w-5 h-5"/></Link></div><div className="relative"><img src="https://images.pexels.com/photos/5207102/pexels-photo-5207102.jpeg?auto=compress&dpr=1&h=750&w=1260" alt="Equipo sanitario trabajando de forma coordinada" className="w-full h-[440px] object-cover rounded-3xl shadow-2xl"/><div className="absolute -bottom-5 left-5 right-5 bg-white text-slate-900 rounded-2xl shadow-xl p-5 flex items-center gap-4"><HeartPulse className="w-9 h-9 text-[#005EB8]"/><p className="font-semibold">Servicios diseñados alrededor del centro, no al revés.</p></div></div></div></section>
  <section className="py-20 bg-white"><div className="max-w-6xl mx-auto px-6 grid lg:grid-cols-2 gap-14"><div><p className="text-[#005EB8] font-semibold uppercase tracking-wide text-sm">Nuestro enfoque</p><h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mt-2">Una estructura sanitaria clara, delimitada y utilizable</h2><div className="space-y-5 mt-7 text-lg text-slate-600 leading-relaxed"><p>GASI puede configurar servicios con enfermería presencial, apoyo médico remoto asociado, fisioterapia, psicología y formación sanitaria, según las necesidades de cada cliente y el alcance autorizado.</p><p>La propuesta concreta define quién interviene, dónde, en qué horario, con qué recursos y cómo se escala una situación cuando supera el alcance del profesional presente.</p><p>No presentamos esta oferta como servicio de prevención ajeno ni como vigilancia de la salud. Tampoco incluimos reconocimientos médicos laborales, evaluación de riesgos ni gestión de bajas.</p></div></div><div className="grid sm:grid-cols-2 gap-5">{principles.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border bg-slate-50 p-6"><div className="w-11 h-11 rounded-xl bg-[#005EB8]/10 text-[#005EB8] flex items-center justify-center"><Icon className="w-6 h-6"/></div><h3 className="font-bold text-xl text-slate-900 mt-4">{title}</h3><p className="text-slate-600 mt-2">{text}</p></article>)}</div></div></section>
  <section className="py-20 bg-[#F3F7FB]"><div className="max-w-6xl mx-auto px-6"><div className="max-w-3xl"><p className="text-[#005EB8] font-semibold uppercase tracking-wide text-sm">Cómo tomamos decisiones</p><h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mt-2">Primero necesidad; después recursos</h2><p className="text-lg text-slate-600 mt-5">No incorporamos profesionales por catálogo. La configuración se construye a partir de la actividad del centro, la cobertura que necesita y la capacidad que GASI puede prestar con seguridad.</p></div><div className="grid md:grid-cols-3 gap-6 mt-10">{[
   ['1','Entender el centro','Actividad, turnos, número de trabajadores, distribución y patrón de incidencias.'],
   ['2','Definir la cobertura','Profesionales, horarios, equipamiento y circuitos de coordinación.'],
   ['3','Ponerla en marcha','Accesos, protocolos, trazabilidad, responsables y revisión del servicio.']
  ].map(([n,t,d])=><div key={n} className="rounded-2xl bg-white border p-7"><span className="w-9 h-9 rounded-full bg-[#005EB8] text-white flex items-center justify-center font-bold">{n}</span><h3 className="text-xl font-bold text-slate-900 mt-5">{t}</h3><p className="text-slate-600 mt-2">{d}</p></div>)}</div></div></section>
  <section className="py-20 bg-[#005EB8] text-white"><div className="max-w-4xl mx-auto px-6 text-center"><h2 className="text-3xl lg:text-4xl font-bold">¿Quiere estudiar una cobertura sanitaria para su organización?</h2><p className="text-xl text-white/85 mt-5">Cuéntenos cómo funciona el centro y le diremos qué configuración tendría sentido.</p><Link to="/contacto" className="inline-flex items-center mt-8 bg-white text-[#005EB8] font-bold px-7 py-3 rounded-xl">Contactar <ArrowRight className="ml-2 w-5 h-5"/></Link></div></section>
 </div>;
}
