import React from'react';
import{Link}from'react-router-dom';
import{ArrowRight,Brain,Heart,Network,Stethoscope,Users}from'lucide-react';

const services=[
 {icon:Stethoscope,title:'Enfermería presencial',text:'Puede actuar como núcleo del dispositivo sanitario del centro cuando la cobertura lo requiere.'},
 {icon:Network,title:'Apoyo médico remoto',text:'Se incorpora cuando la configuración necesita apoyo facultativo para valoración, coordinación o escalado.'},
 {icon:Heart,title:'Fisioterapia',text:'Puede añadirse en centros donde la carga física o el perfil de actividad justifiquen este recurso.'},
 {icon:Brain,title:'Psicología',text:'Atención puntual cuando una persona necesita apoyo dentro del marco acordado. El seguimiento continuado se deriva fuera del servicio corporativo ordinario.'},
 {icon:Users,title:'Coordinación asistencial',text:'Profesionales y circuitos se organizan como un servicio único, con responsabilidades y accesos diferenciados.'}
];

export default function SaludLaboral(){
 return <div data-testid="salud-laboral-page">
  <section className="bg-slate-950 text-white py-20"><div className="max-w-7xl mx-auto px-6 grid lg:grid-cols-[1fr_.9fr] gap-12 items-center"><div><p className="text-cyan-300 font-semibold uppercase tracking-wide text-sm">Servicios sanitarios para organizaciones</p><h1 className="text-4xl lg:text-6xl font-bold mt-3">Más allá de la enfermería cuando el centro realmente lo necesita</h1><p className="text-xl text-slate-300 mt-6">Fisioterapia, psicología y apoyo médico remoto pueden integrarse en una cobertura sanitaria concreta. No se ofrecen como un catálogo automático: se incorporan cuando tienen sentido operativo y asistencial.</p><Link to="/contacto" className="inline-flex items-center mt-8 bg-white text-[#005EB8] font-bold px-6 py-3 rounded-xl">Estudiar una configuración <ArrowRight className="ml-2 w-5 h-5"/></Link></div><div className="grid grid-cols-2 gap-4"><img src="https://images.pexels.com/photos/5793695/pexels-photo-5793695.jpeg?auto=compress&dpr=1&h=750&w=1260" alt="Sesión de fisioterapia" loading="lazy" decoding="async" className="w-full h-[360px] object-cover rounded-3xl col-span-2"/><img src="https://images.pexels.com/photos/3881422/pexels-photo-3881422.jpeg?auto=compress&dpr=1&h=750&w=1260" alt="Profesional sanitario trabajando con apoyo digital" loading="lazy" decoding="async" className="w-full h-48 object-cover rounded-2xl"/><div className="rounded-2xl bg-[#005EB8] p-6 flex items-end"><p className="font-semibold text-lg">Un mismo servicio, con recursos distintos según cada centro.</p></div></div></div></section>
  <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-6"><div className="max-w-3xl"><h2 className="text-3xl lg:text-4xl font-bold text-slate-900">Líneas que pueden formar parte de la cobertura</h2><p className="text-lg text-slate-600 mt-5">La propuesta identifica qué recurso se incorpora, con qué función y en qué condiciones. Eso evita solapamientos y mantiene claro qué puede hacer cada profesional.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mt-12">{services.map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border p-7"><div className="w-12 h-12 rounded-xl bg-[#005EB8]/10 text-[#005EB8] flex items-center justify-center"><Icon className="w-6 h-6"/></div><h3 className="text-xl font-bold text-slate-900 mt-5">{title}</h3><p className="text-slate-600 mt-3 leading-relaxed">{text}</p></article>)}</div></div></section>
  <section className="py-20 bg-[#F3F7FB]"><div className="max-w-6xl mx-auto px-6 grid lg:grid-cols-2 gap-12 items-start"><div><p className="text-[#005EB8] font-semibold uppercase tracking-wide text-sm">Qué no es este servicio</p><h2 className="text-3xl font-bold text-slate-900 mt-2">Límites claros desde la propuesta</h2><p className="text-lg text-slate-600 mt-5">GASI no presenta esta oferta como servicio de prevención ajeno ni como vigilancia de la salud. Tampoco incluye reconocimientos médicos laborales, evaluación de riesgos ni gestión de bajas.</p></div><div className="rounded-3xl bg-white border p-8"><h3 className="text-xl font-bold text-slate-900">La pregunta útil no es “qué podemos meter”, sino “qué necesita este centro”.</h3><p className="text-slate-600 mt-4">Carga física, turnicidad, distribución de trabajadores, tipo de actividad y patrón de incidencias ayudan a decidir si conviene añadir fisioterapia, psicología, apoyo médico u otros recursos.</p></div></div></section>
 </div>;
}
