import React from'react';
import{Link}from'react-router-dom';
import{ArrowRight,Building2,GraduationCap,HeartPulse}from'lucide-react';

const services=[
 {title:'Cobertura sanitaria en el centro de trabajo',eyebrow:'Presencia asistencial',icon:Building2,image:'https://images.pexels.com/photos/3952137/pexels-photo-3952137.jpeg?auto=compress&dpr=1&h=750&w=1260',description:'Enfermería presencial integrada en el centro, con horarios y recursos definidos para cada servicio. Cuando la configuración lo contempla, puede incorporar apoyo médico remoto para valoración y coordinación.',points:['Enfermería presencial','Atención sanitaria dentro del alcance contratado','Escalado y coordinación asistencial','Configuración por centro y turnos'],link:'/cobertura-sanitaria'},
 {title:'Servicios sanitarios complementarios',eyebrow:'Según necesidades del centro',icon:HeartPulse,image:'https://images.pexels.com/photos/5793695/pexels-photo-5793695.jpeg?auto=compress&dpr=1&h=750&w=1260',description:'Fisioterapia y psicología pueden incorporarse a la cobertura cuando aportan valor al perfil de actividad del centro. No se incluyen de forma automática: se definen en la propuesta concreta.',points:['Fisioterapia','Atención psicológica puntual','Coordinación con enfermería','Alcance profesional delimitado'],link:'/servicios-sanitarios-organizaciones'},
 {title:'Formación sanitaria',eyebrow:'Equipos mejor preparados',icon:GraduationCap,image:'https://images.pexels.com/photos/36346116/pexels-photo-36346116/free-photo-of-hands-on-cpr-training-session-in-buenos-aires.jpeg?auto=compress&dpr=1&h=750&w=1260',description:'Formación práctica para empresas y profesionales: primeros auxilios, reanimación cardiopulmonar, respuesta inicial ante urgencias y programas adaptados a riesgos y necesidades del entorno.',points:['Primeros auxilios','Reanimación cardiopulmonar y soporte vital básico','Detección del deterioro clínico','Programas a medida'],link:'/formacion-sanitaria'}
];

export default function Servicios(){
 return <div data-testid="servicios-page">
  <section className="bg-slate-950 text-white py-24"><div className="max-w-6xl mx-auto px-6"><p className="text-cyan-300 font-semibold tracking-wide uppercase text-sm">GASI · Servicios sanitarios B2B</p><h1 className="text-4xl lg:text-6xl font-bold mt-3 max-w-4xl">Cobertura sanitaria diseñada alrededor de cada centro de trabajo</h1><p className="text-xl text-slate-300 mt-6 max-w-3xl">No partimos de un paquete cerrado. Revisamos actividad, turnos y necesidades para definir qué profesionales y circuitos tienen sentido en cada servicio.</p></div></section>
  <section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-6 space-y-24">{services.map((s,i)=>{const Icon=s.icon;return <article key={s.title} className={`grid lg:grid-cols-2 gap-12 items-center ${i%2?'lg:[&>*:first-child]:order-2':''}`}>
   <div className="relative"><img src={s.image} alt="" className="w-full h-[390px] object-cover rounded-3xl shadow-xl"/><div className="absolute -bottom-5 left-6 rounded-2xl bg-white shadow-lg border px-5 py-4 flex items-center gap-3"><span className="w-11 h-11 rounded-xl bg-[#005EB8]/10 text-[#005EB8] flex items-center justify-center"><Icon className="w-6 h-6"/></span><span className="font-semibold text-slate-900">{s.eyebrow}</span></div></div>
   <div><p className="text-[#005EB8] font-semibold text-sm uppercase tracking-wide">{s.eyebrow}</p><h2 className="text-3xl lg:text-4xl font-bold text-slate-900 mt-2">{s.title}</h2><p className="text-lg text-slate-600 leading-relaxed mt-5">{s.description}</p><ul className="grid sm:grid-cols-2 gap-3 mt-7">{s.points.map(p=><li key={p} className="rounded-xl bg-slate-50 border px-4 py-3 text-slate-700">✓ {p}</li>)}</ul><Link to={s.link} className="inline-flex items-center gap-2 mt-8 text-[#005EB8] font-bold">Ver servicio <ArrowRight className="w-5 h-5"/></Link></div>
  </article>})}</div></section>
  <section className="py-18 bg-[#F3F7FB]"><div className="max-w-5xl mx-auto px-6 py-16 text-center"><h2 className="text-3xl lg:text-4xl font-bold text-slate-900">Primero entendemos el centro. Después configuramos el servicio.</h2><p className="text-lg text-slate-600 mt-5">La propuesta concreta define cobertura, profesionales, horarios, circuitos de coordinación y condiciones de puesta en marcha.</p><Link to="/contacto" className="inline-flex mt-8 bg-[#005EB8] hover:bg-[#004a92] text-white font-semibold px-7 py-3 rounded-xl">Cuéntenos qué necesita <ArrowRight className="ml-2 w-5 h-5"/></Link></div></section>
 </div>;
}
