import React,{createContext,useCallback,useContext,useEffect,useState}from'react';
const InternalAuthContext=createContext(null),MASTER_ID='GASI-MASTER-01';
const ROLE_LABELS={nurse:'Enfermería',physician:'Facultativo',psychologist:'Psicología',physiotherapist:'Fisioterapia',admin:'Administración / Coordinación'};
const apiRoot=()=>String(process.env.REACT_APP_BACKEND_URL||'').replace(/\/$/,'');
const canManage=a=>Boolean(a&&(a.id===MASTER_ID||a.delegatedPrivileges?.includes('worker_access_management')));
const mapWorker=w=>({id:w.id,displayName:w.display_name,role:w.role,roleLabel:ROLE_LABELS[w.role]||w.role,centers:w.centers||[],status:w.active===false?'REVOKED':'ACTIVE',delegatedPrivileges:w.delegated_privileges||[]});
const authHeaders=(token,json=false)=>({...json?{'Content-Type':'application/json'}:{},Authorization:`Bearer ${token}`});
export function InternalPrototypeAuthProvider({children}){
 const[identities,setIdentities]=useState([]),[session,setSession]=useState(null),[token,setToken]=useState(null),[lastError,setLastError]=useState(''),[sessionChecking,setSessionChecking]=useState(false),[directoryLoading,setDirectoryLoading]=useState(false);
 const clear=useCallback(()=>{setSession(null);setToken(null);setIdentities([]);},[]);
 const refreshDirectory=useCallback(async(actor=session,sessionToken=token)=>{if(!actor||!sessionToken||!canManage(actor))return{ok:false,error:'Sin privilegio para gestionar trabajadores.'};setDirectoryLoading(true);try{const r=await fetch(`${apiRoot()}/api/internal-clinical/workers`,{headers:authHeaders(sessionToken),cache:'no-store'});if(r.status===401){clear();return{ok:false,error:'La sesión ha caducado o ha sido revocada.'};}if(!r.ok)return{ok:false,error:`Directorio rechazado (HTTP ${r.status}).`};setIdentities((await r.json()).map(mapWorker));return{ok:true};}catch(_){return{ok:false,error:'Servicio no disponible.'};}finally{setDirectoryLoading(false);}},[session,token,clear]);
 const signIn=async(workerId,password)=>{setSessionChecking(true);setLastError('');try{const r=await fetch(`${apiRoot()}/api/internal-clinical/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:workerId,password})});if(!r.ok){setLastError('Credenciales incorrectas o acceso revocado.');return false;}const data=await r.json(),profile=mapWorker(data.profile);setToken(data.token);setSession({...profile,signedInAt:new Date().toISOString(),expiresAt:data.expires_at});if(canManage(profile))await refreshDirectory(profile,data.token);return true;}catch(_){setLastError('No se puede conectar con el servicio de acceso.');return false;}finally{setSessionChecking(false);}};
 const validateSession=useCallback(async()=>{if(!token)return false;setSessionChecking(true);try{const r=await fetch(`${apiRoot()}/api/internal-clinical/session`,{headers:authHeaders(token),cache:'no-store'});if(!r.ok){clear();setLastError('La sesión ha caducado o ha sido revocada.');return false;}const profile=mapWorker(await r.json());setSession(current=>({...current,...profile}));return true;}catch(_){setLastError('No se puede validar la sesión.');return false;}finally{setSessionChecking(false);}},[token,clear]);
 const signOut=async()=>{const t=token;clear();if(t)try{await fetch(`${apiRoot()}/api/internal-clinical/logout`,{method:'POST',headers:authHeaders(t)});}catch(_){}};
 useEffect(()=>{if(!token)return;const id=setInterval(validateSession,60000);return()=>clearInterval(id);},[token,validateSession]);
 const grantPrivilege=async(id,privilege,grant=true)=>{if(session?.id!==MASTER_ID)return{ok:false,error:'Solo la cuenta maestra puede cambiar privilegios.'};try{const r=await fetch(`${apiRoot()}/api/internal-clinical/workers/${encodeURIComponent(id)}/privileges/${grant?'grant':'revoke'}`,{method:'POST',headers:authHeaders(token,true),body:JSON.stringify({privilege,reason:'Delegación desde panel maestro'})});if(!r.ok)return{ok:false,error:`Operación rechazada (HTTP ${r.status}).`};return refreshDirectory(session,token);}catch(_){return{ok:false,error:'No se pudo confirmar el privilegio.'};}};
 const addIdentity=async({displayName,role,centers,temporaryPassword})=>{if(!canManage(session))return{ok:false,error:'Sin permiso de gestión.'};const id=`GASI-${role.toUpperCase()}-${Date.now()}`;try{const r=await fetch(`${apiRoot()}/api/internal-clinical/workers`,{method:'POST',headers:authHeaders(token,true),body:JSON.stringify({id,display_name:displayName,role,centers,temporary_password:temporaryPassword})});if(!r.ok)return{ok:false,error:`Alta rechazada (HTTP ${r.status}).`};await refreshDirectory(session,token);return{ok:true,identity:mapWorker(await r.json())};}catch(_){return{ok:false,error:'Alta no confirmada.'};}};
 const setIdentityStatus=async(id,state)=>{if(!canManage(session))return{ok:false,error:'Sin permiso de gestión.'};try{const r=await fetch(`${apiRoot()}/api/internal-clinical/workers/${encodeURIComponent(id)}/access`,{method:'POST',headers:authHeaders(token,true),body:JSON.stringify({state})});if(!r.ok)return{ok:false,error:`Cambio rechazado (HTTP ${r.status}).`};await refreshDirectory(session,token);return{ok:true};}catch(_){return{ok:false,error:'Cambio no confirmado.'};}};
 const value={session,token,identities,lastError,sessionChecking,directoryLoading,signIn,signOut,validateSession,refreshDirectory,addIdentity,setIdentityStatus,grantPrivilege,isAuthenticated:Boolean(session&&token),isMaster:session?.id===MASTER_ID,canManageWorkers:canManage(session)};
 return <InternalAuthContext.Provider value={value}>{children}</InternalAuthContext.Provider>;
}
export function useInternalPrototypeAuth(){const value=useContext(InternalAuthContext);if(!value)throw new Error('provider required');return value;}
