import{EPISODE_STATUS,MESSAGE_STATUS,INTERNAL_ROLES,appendMessageStatus,canCloseSyntheticEpisode,closeSyntheticEpisode,createSyntheticEpisode,respondToSyntheticEpisode,visibleEpisodeFieldsForRole}from'./internalClinicalModel';
const nurse={id:'USR-NURSE-TEST',role:INTERNAL_ROLES.NURSE},physician={id:'USR-PHYS-TEST',role:INTERNAL_ROLES.PHYSICIAN},psychologist={id:'USR-PSY-TEST',role:INTERNAL_ROLES.PSYCHOLOGIST},physio={id:'USR-PHYSIO-TEST',role:INTERNAL_ROLES.PHYSIOTHERAPIST},admin={id:'USR-ADMIN-TEST',role:INTERNAL_ROLES.ADMIN};
const makeEpisode=(actor=nurse)=>createSyntheticEpisode({id:`CASE-${actor.role}`,patientRef:'PATIENT-SYNTHETIC-001',center:'Centro ficticio Madrid 01',level:2,summary:'Caso sintético de prueba.',actor,at:'2026-09-12T18:00:00.000Z'});
test('nursing, psychology and physiotherapy can create discipline-specific synthetic episodes',()=>{expect(makeEpisode(nurse).discipline).toBe('nursing');expect(makeEpisode(psychologist).discipline).toBe('psychology');expect(makeEpisode(physio).discipline).toBe('physiotherapy');expect(()=>makeEpisode(physician)).toThrow('invalid_episode_input');expect(()=>makeEpisode(admin)).toThrow('invalid_episode_input');});
test('only physician can issue a medical response',()=>{for(const actor of[nurse,psychologist,physio,admin])expect(()=>respondToSyntheticEpisode(makeEpisode(),{text:'Respuesta sintética.',actor})).toThrow('response_not_allowed');expect(respondToSyntheticEpisode(makeEpisode(),{text:'Respuesta sintética.',actor:physician}).status).toBe(EPISODE_STATUS.RESPONDED);});
test('a clinical response changes episode status but message is only EMITIDA',()=>{const e=respondToSyntheticEpisode(makeEpisode(),{text:'Respuesta sintética.',actor:physician});expect(e.status).toBe(EPISODE_STATUS.RESPONDED);expect(e.responses[0].status).toBe(MESSAGE_STATUS.ISSUED);});
test('delivery and read states require technical evidence',()=>{const m=respondToSyntheticEpisode(makeEpisode(),{text:'Respuesta sintética.',actor:physician}).responses[0];expect(()=>appendMessageStatus(m,MESSAGE_STATUS.DELIVERED,physician)).toThrow('invalid_message_status_transition');const d=appendMessageStatus(m,MESSAGE_STATUS.DELIVERED,physician,{kind:'transport_receipt',at:'2026-09-12T18:02:00.000Z'});expect(()=>appendMessageStatus(d,MESSAGE_STATUS.READ,nurse)).toThrow('invalid_message_status_transition');expect(appendMessageStatus(d,MESSAGE_STATUS.READ,nurse,{kind:'authenticated_acknowledgement',at:'2026-09-12T18:03:00.000Z'}).status).toBe(MESSAGE_STATUS.READ);});
test('an episode does not close while follow-up is pending',()=>{const e=respondToSyntheticEpisode(makeEpisode(),{text:'Respuesta sintética.',actor:physician});expect(canCloseSyntheticEpisode(e,{followUpPending:true})).toBe(false);expect(()=>closeSyntheticEpisode(e,{actor:nurse,followUpPending:true})).toThrow('close_not_allowed');});
test('admin projection excludes clinical narrative and response content',()=>{const e=respondToSyntheticEpisode(makeEpisode(psychologist),{text:'Respuesta sintética sensible.',actor:physician});const v=visibleEpisodeFieldsForRole(e,admin.role);expect(v.summary).toBeUndefined();expect(v.responses).toBeUndefined();expect(v.patientRef).toBeUndefined();expect(v.discipline).toBe('psychology');});
