import { createInternalClinicalApi, InternalClinicalApiError, snakeToCamelEpisode } from './internalClinicalApi';
const jsonResponse=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});
const TOKEN='signed-session-token';
describe('internalClinicalApi',()=>{
 test('requires an authenticated session',()=>{expect(()=>createInternalClinicalApi({token:''})).toThrow(InternalClinicalApiError);});
 test('sends bearer session and creates an episode against a stable patient id',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({id:'GASI-EP-000001',patient_id:'GASI-PT-00000001',patient_ref:'GASI-HC-00000001',center:'Centro GASI Madrid 01',level:2,status:'ABIERTO',created_at:'2026-09-17T20:30:00Z',created_by_id:'GASI-NURSE-01',responses:[],addenda:[],level_history:[],disposition_events:[]},201));const api=createInternalClinicalApi({token:TOKEN,baseUrl:'https://clinical.gasi.invalid',fetchImpl});const episode=await api.createEpisode({patientId:'GASI-PT-00000001',center:'Centro GASI Madrid 01',level:2,summary:'Valoración clínica'});expect(fetchImpl).toHaveBeenCalledWith('https://clinical.gasi.invalid/api/internal-clinical/episodes',expect.objectContaining({method:'POST',headers:expect.objectContaining({Authorization:`Bearer ${TOKEN}`}),body:JSON.stringify({patient_id:'GASI-PT-00000001',center:'Centro GASI Madrid 01',level:2,summary:'Valoración clínica'})}));expect(episode.patientId).toBe('GASI-PT-00000001');expect(episode.patientRef).toBe('GASI-HC-00000001');expect(episode.createdById).toBe('GASI-NURSE-01');});
 test('searches patients and normalizes history fields',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse([{id:'GASI-PT-00000001',medical_record_number:'GASI-HC-00000001',given_name:'Javier',family_name:'Suárez',employee_number:'EMP-1',episode_count:2,match_score:.91}]));const api=createInternalClinicalApi({token:TOKEN,baseUrl:'https://clinical.gasi.invalid',fetchImpl});const rows=await api.searchPatients('Javi Suarez');expect(fetchImpl).toHaveBeenCalledWith('https://clinical.gasi.invalid/api/internal-clinical/patients/search?q=Javi%20Suarez',expect.objectContaining({headers:expect.objectContaining({Authorization:`Bearer ${TOKEN}`})}));expect(rows[0]).toMatchObject({medicalRecordNumber:'GASI-HC-00000001',givenName:'Javier',familyName:'Suárez',employeeNumber:'EMP-1',episodeCount:2,matchScore:.91});});
 test('normalizes nested backend structures without inventing data',()=>{const normalized=snakeToCamelEpisode({id:'GASI-EP-000002',level_history:[{at:'t1',actor_id:'GASI-NURSE-01',from:2,to:1}],disposition_events:[{id:'D1',kind:'TRASLADO',occurred_at:'t2',recorded_at:'t3',recorded_by_id:'GASI-NURSE-01',recorded_by_role:'nurse'}],responses:[{id:'R1',author_id:'GASI-PHYS-01',created_at:'t4',status:'EMITIDA',status_history:[],late_after_disposition:true,disposition_event_id:'D1',late_reviewed_at:null,late_reviewed_by_id:null}],addenda:[{id:'A1',author_id:'GASI-NURSE-01',author_role:'nurse',created_at:'t5',text:'Evolución'}]});expect(normalized.levelHistory[0].actorId).toBe('GASI-NURSE-01');expect(normalized.dispositionEvents[0].occurredAt).toBe('t2');expect(normalized.responses[0].lateAfterDisposition).toBe(true);expect(normalized.addenda[0].authorRole).toBe('nurse');});
 test('maps privileged access read-only state from the backend envelope',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({id:'GASI-EP-000003',status:'ABIERTO',privileged_access:{read_only:true,reason:'inspection',reference:'REF-1'}}));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});const episode=await api.privilegedRead('GASI-EP-000003',{reason:'inspection',reference:'REF-1'});expect(episode.readOnly).toBe(true);expect(episode.privilegedAccess).toBe(true);});
 test('fails closed on network errors',async()=>{const fetchImpl=jest.fn().mockRejectedValue(new Error('offline'));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});await expect(api.listEpisodes()).rejects.toMatchObject({name:'InternalClinicalApiError',code:'network_unavailable',status:0});});
 test('surfaces safe backend error codes without returning clinical response bodies',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({detail:'closed_episode_immutable',secret:'do-not-expose'},409));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});await expect(api.changeLevel('GASI-EP-000001',3)).rejects.toMatchObject({code:'closed_episode_immutable',status:409,message:'La operación clínica no pudo completarse.'});});
 test('uses explicit delivery evidence transitions',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({status:'ENTREGADA'}));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});await api.advanceMessage('GASI-EP-000001','GASI-EP-000001-R1','delivery_receipt');expect(fetchImpl).toHaveBeenCalledWith('/api/internal-clinical/episodes/GASI-EP-000001/responses/GASI-EP-000001-R1/delivery',expect.objectContaining({method:'POST',headers:expect.objectContaining({Authorization:`Bearer ${TOKEN}`}),body:JSON.stringify({kind:'delivery_receipt'})}));});
});
