export const EPISODE_STATUS=Object.freeze({OPEN:'ABIERTO',RESPONDED:'RESPONDIDO',CLOSED:'CERRADO'});
export const MESSAGE_STATUS=Object.freeze({DRAFT:'BORRADOR',ISSUED:'EMITIDA',DELIVERED:'ENTREGADA',READ:'LEIDA'});
export const INTERNAL_ROLES=Object.freeze({NURSE:'nurse',PHYSICIAN:'physician',PSYCHOLOGIST:'psychologist',PHYSIOTHERAPIST:'physiotherapist',ADMIN:'admin'});
export const CLINICAL_LEVELS=Object.freeze([1,2,3]);
export const EPISODE_CREATORS=Object.freeze([INTERNAL_ROLES.NURSE,INTERNAL_ROLES.PSYCHOLOGIST,INTERNAL_ROLES.PHYSIOTHERAPIST]);
export const DISCIPLINE_BY_ROLE=Object.freeze({[INTERNAL_ROLES.NURSE]:'nursing',[INTERNAL_ROLES.PSYCHOLOGIST]:'psychology',[INTERNAL_ROLES.PHYSIOTHERAPIST]:'physiotherapy'});
const MESSAGE_TRANSITIONS=Object.freeze({[MESSAGE_STATUS.DRAFT]:[MESSAGE_STATUS.ISSUED],[MESSAGE_STATUS.ISSUED]:[MESSAGE_STATUS.DELIVERED],[MESSAGE_STATUS.DELIVERED]:[MESSAGE_STATUS.READ],[MESSAGE_STATUS.READ]:[]});
export function canTransitionMessageStatus(current,next,evidence=null){if(!MESSAGE_TRANSITIONS[current]?.includes(next))return false;if([MESSAGE_STATUS.DELIVERED,MESSAGE_STATUS.READ].includes(next))return Boolean(evidence&&evidence.kind&&evidence.at);return true;}
export function appendMessageStatus(message,nextStatus,actor,evidence=null,at=new Date().toISOString()){const current=message.status||MESSAGE_STATUS.DRAFT;if(!canTransitionMessageStatus(current,nextStatus,evidence))throw new Error('invalid_message_status_transition');return{...message,status:nextStatus,statusHistory:[...(message.statusHistory||[]),{at,actorId:actor.id,actorRole:actor.role,from:current,to:nextStatus,evidence:evidence?{kind:evidence.kind,at:evidence.at}:null}]};}
export function createSyntheticEpisode({id,patientRef,center,level,summary,actor,at=new Date().toISOString()}){if(!id||!patientRef||!center||!summary||!EPISODE_CREATORS.includes(actor?.role)||!CLINICAL_LEVELS.includes(level))throw new Error('invalid_episode_input');return{id,patientRef,center,level,status:EPISODE_STATUS.OPEN,discipline:DISCIPLINE_BY_ROLE[actor.role],summary,createdAt:at,createdById:actor.id,responses:[],addenda:[],levelHistory:[],audit:[{at,actorId:actor.id,actorRole:actor.role,action:`EPISODE_CREATED_${DISCIPLINE_BY_ROLE[actor.role]}_N${level}`}]};}
export function respondToSyntheticEpisode(episode,{text,actor,at=new Date().toISOString()}){if(actor?.role!==INTERNAL_ROLES.PHYSICIAN||!text?.trim()||episode.status===EPISODE_STATUS.CLOSED)throw new Error('response_not_allowed');const response={id:`${episode.id}-R${episode.responses.length+1}`,text:text.trim(),authorId:actor.id,createdAt:at,status:MESSAGE_STATUS.ISSUED,statusHistory:[{at,actorId:actor.id,actorRole:actor.role,from:MESSAGE_STATUS.DRAFT,to:MESSAGE_STATUS.ISSUED,evidence:null}]};return{...episode,status:EPISODE_STATUS.RESPONDED,responses:[...episode.responses,response],audit:[...episode.audit,{at,actorId:actor.id,actorRole:actor.role,action:'CLINICAL_RESPONSE_ISSUED'}]};}
export function canCloseSyntheticEpisode(episode,{followUpPending=false,acknowledgementRequired=false}={}){if(episode.status!==EPISODE_STATUS.RESPONDED||episode.responses.length===0||followUpPending)return false;if(!acknowledgementRequired)return true;return episode.responses[episode.responses.length-1].status===MESSAGE_STATUS.READ;}
export function closeSyntheticEpisode(episode,{actor,followUpPending=false,acknowledgementRequired=false,at=new Date().toISOString()}){if(![INTERNAL_ROLES.NURSE,INTERNAL_ROLES.PHYSICIAN].includes(actor?.role)||!canCloseSyntheticEpisode(episode,{followUpPending,acknowledgementRequired}))throw new Error('close_not_allowed');return{...episode,status:EPISODE_STATUS.CLOSED,closedAt:at,closedById:actor.id,audit:[...episode.audit,{at,actorId:actor.id,actorRole:actor.role,action:'EPISODE_CLOSED'}]};}
export function visibleEpisodeFieldsForRole(episode,role){if(role!==INTERNAL_ROLES.ADMIN)return episode;return{id:episode.id,center:episode.center,level:episode.level,status:episode.status,discipline:episode.discipline,createdAt:episode.createdAt,createdById:episode.createdById,closedAt:episode.closedAt||null,closedById:episode.closedById||null};}
