import { interpretSessionAuthority, SESSION_AUTHORITY_CODES } from './internalSessionAuthority';
const candidate={id:'USR-DEMO-NURSE-01',role:'nurse'};
describe('interpretSessionAuthority',()=>{
 test('accepts only a matching active authoritative identity',()=>{const result=interpretSessionAuthority({candidate,httpStatus:200,authoritative:{id:candidate.id,role:candidate.role,active:true,centers:['Centro ficticio Madrid 01'],delegated_privileges:[]}});expect(result).toEqual({ok:true,code:SESSION_AUTHORITY_CODES.OK,message:'',centers:['Centro ficticio Madrid 01'],delegatedPrivileges:[]});});
 test('takes delegated privileges only from authoritative session payload',()=>{const result=interpretSessionAuthority({candidate:{...candidate,delegatedPrivileges:['clinical_record_privileged_read']},httpStatus:200,authoritative:{id:candidate.id,role:candidate.role,active:true,centers:['Centro ficticio Madrid 01'],delegated_privileges:['worker_access_management']}});expect(result.ok).toBe(true);expect(result.delegatedPrivileges).toEqual(['worker_access_management']);});
 test('fails closed when the authority revokes the identity',()=>{const result=interpretSessionAuthority({candidate,httpStatus:401});expect(result.ok).toBe(false);expect(result.code).toBe(SESSION_AUTHORITY_CODES.REVOKED);});
 test('fails closed when the authority is unavailable',()=>{const result=interpretSessionAuthority({candidate,networkError:true});expect(result.ok).toBe(false);expect(result.code).toBe(SESSION_AUTHORITY_CODES.UNAVAILABLE);});
 test('rejects role drift even with HTTP 200',()=>{const result=interpretSessionAuthority({candidate,httpStatus:200,authoritative:{id:candidate.id,role:'physician',active:true,centers:['Centro ficticio Madrid 01']}});expect(result.ok).toBe(false);expect(result.code).toBe(SESSION_AUTHORITY_CODES.MISMATCH);});
 test('rejects an inactive authoritative payload',()=>{const result=interpretSessionAuthority({candidate,httpStatus:200,authoritative:{id:candidate.id,role:candidate.role,active:false,centers:['Centro ficticio Madrid 01']}});expect(result.ok).toBe(false);expect(result.code).toBe(SESSION_AUTHORITY_CODES.MISMATCH);});
 test('treats unexpected backend statuses as denial',()=>{const result=interpretSessionAuthority({candidate,httpStatus:503});expect(result.ok).toBe(false);expect(result.code).toBe(SESSION_AUTHORITY_CODES.REJECTED);});
});
