import { createInternalClinicalApi, InternalClinicalApiError, snakeToCamelEpisode } from './internalClinicalApi';
const jsonResponse=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body});
const TOKEN='signed-session-token';
describe('internalClinicalApi',()=>{
 test('requires an authenticated session',()=>{expect(()=>createInternalClinicalApi({token:''})).toThrow(InternalClinicalApiError);});
 test('sends bearer session and creates an episode with backend field names',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({id:'GASI-EP-000001',patient_ref:'PAC-001',center:'Centro GASI Madrid 01',level:2,status:'ABIERTO',created_at:'2026-09-17T20:30:00Z',created_by_id:'GASI-NURSE-01',responses:[],addenda:[],level_history:[],disposition_events:[]},201));const api=createInternalClinicalApi({token:TOKEN,baseUrl:'https://clinical.gasi.invalid',fetchImpl});const episode=await api.createEpisode({patientRef:'PAC-001',center:'Centro GASI Madrid 01',level:2,summary:'Valoración clínica'});expect(fetchImpl).toHaveBeenCalledWith('https://clinical.gasi.invalid/api/internal-clinical/episodes',expect.objectContaining({method:'POST',headers:expect.objectContaining({Authorization:`Bearer ${TOKEN}`}),body:JSON.stringify({patient_ref:'PAC-001',center:'Centro GASI Madrid 01',level:2,summary:'Valoración clínica'})}));expect(episode.patientRef).toBe('PAC-001');expect(episode.createdById).toBe('GASI-NURSE-01');});
 test('normalizes nested backend structures without inventing data',()=>{const normalized=snakeToCamelEpisode({id:'GASI-EP-000002',level_history:[{at:'t1',actor_id:'GASI-NURSE-01',from:2,to:1}],disposition_events:[{id:'D1',kind:'TRASLADO',occurred_at:'t2',recorded_at:'t3',recorded_by_id:'GASI-NURSE-01',recorded_by_role:'nurse'}],responses:[{id:'R1',author_id:'GASI-PHYS-01',created_at:'t4',status:'EMITIDA',status_history:[],late_after_disposition:true,disposition_event_id:'D1',late_reviewed_at:null,late_reviewed_by_id:null}],addenda:[{id:'A1',author_id:'GASI-NURSE-01',author_role:'nurse',created_at:'t5',text:'Evolución'}]});expect(normalized.levelHistory[0].actorId).toBe('GASI-NURSE-01');expect(normalized.dispositionEvents[0].occurredAt).toBe('t2');expect(normalized.responses[0].lateAfterDisposition).toBe(true);expect(normalized.addenda[0].authorRole).toBe('nurse');});
 test('fails closed on network errors',async()=>{const fetchImpl=jest.fn().mockRejectedValue(new Error('offline'));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});await expect(api.listEpisodes()).rejects.toMatchObject({name:'InternalClinicalApiError',code:'network_unavailable',status:0});});
 test('surfaces safe backend error codes without returning clinical response bodies',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({detail:'closed_episode_immutable',secret:'do-not-expose'},409));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});await expect(api.changeLevel('GASI-EP-000001',3)).rejects.toMatchObject({code:'closed_episode_immutable',status:409,message:'La operación clínica no pudo completarse.'});});
 test('uses explicit delivery evidence transitions',async()=>{const fetchImpl=jest.fn().mockResolvedValue(jsonResponse({status:'ENTREGADA'}));const api=createInternalClinicalApi({token:TOKEN,fetchImpl});await api.advanceMessage('GASI-EP-000001','GASI-EP-000001-R1','delivery_receipt','2026-09-17T20:40:00Z');expect(fetchImpl).toHaveBeenCalledWith('/api/internal-clinical/episodes/GASI-EP-000001/responses/GASI-EP-000001-R1/delivery',expect.objectContaining({method:'POST',headers:expect.objectContaining({Authorization:`Bearer ${TOKEN}`}),body:JSON.stringify({kind:'delivery_receipt',at:'2026-09-17T20:40:00Z'})}));});
});
